/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApplyRouteImport } from './routes/apply'
import { Route as BusinessRouteImport } from './routes/business'
import { Route as ChallengesRouteImport } from './routes/challenges'
import { Route as FriendsRouteImport } from './routes/friends'
import { Route as HomeRouteImport } from './routes/home'
import { Route as JobPreparationRouteImport } from './routes/job-preparation'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as LocationRouteImport } from './routes/location'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as PlanRouteImport } from './routes/plan'
import { Route as ProfessionRouteImport } from './routes/profession'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ResumeAnalyseRouteImport } from './routes/resume-analyse'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ValuePropRouteImport } from './routes/value-prop'
import { Route as BusinessAdvertisingRouteImport } from './routes/business.advertising'
import { Route as BusinessHiringRouteImport } from './routes/business.hiring'
import { Route as BusinessMarketingRouteImport } from './routes/business.marketing'
import { Route as BusinessSalesRouteImport } from './routes/business.sales'
import { Route as BusinessSourcingRouteImport } from './routes/business.sourcing'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyRoute = ApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessRoute = BusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengesRoute = ChallengesRouteImport.update({
  id: '/challenges',
  path: '/challenges',
  getParentRoute: () => rootRouteImport,
} as any)
const FriendsRoute = FriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const JobPreparationRoute = JobPreparationRouteImport.update({
  id: '/job-preparation',
  path: '/job-preparation',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationRoute = LocationRouteImport.update({
  id: '/location',
  path: '/location',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanRoute = PlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfessionRoute = ProfessionRouteImport.update({
  id: '/profession',
  path: '/profession',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeAnalyseRoute = ResumeAnalyseRouteImport.update({
  id: '/resume-analyse',
  path: '/resume-analyse',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ValuePropRoute = ValuePropRouteImport.update({
  id: '/value-prop',
  path: '/value-prop',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessAdvertisingRoute = BusinessAdvertisingRouteImport.update({
  id: '/advertising',
  path: '/advertising',
  getParentRoute: () => BusinessRoute,
} as any)
const BusinessHiringRoute = BusinessHiringRouteImport.update({
  id: '/hiring',
  path: '/hiring',
  getParentRoute: () => BusinessRoute,
} as any)
const BusinessMarketingRoute = BusinessMarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => BusinessRoute,
} as any)
const BusinessSalesRoute = BusinessSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => BusinessRoute,
} as any)
const BusinessSourcingRoute = BusinessSourcingRouteImport.update({
  id: '/sourcing',
  path: '/sourcing',
  getParentRoute: () => BusinessRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apply': typeof ApplyRoute
  '/business': typeof BusinessRouteWithChildren
  '/challenges': typeof ChallengesRoute
  '/friends': typeof FriendsRoute
  '/home': typeof HomeRoute
  '/job-preparation': typeof JobPreparationRoute
  '/leaderboard': typeof LeaderboardRoute
  '/location': typeof LocationRoute
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/plan': typeof PlanRoute
  '/profession': typeof ProfessionRoute
  '/profile': typeof ProfileRoute
  '/resume-analyse': typeof ResumeAnalyseRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/value-prop': typeof ValuePropRoute
  '/business/advertising': typeof BusinessAdvertisingRoute
  '/business/hiring': typeof BusinessHiringRoute
  '/business/marketing': typeof BusinessMarketingRoute
  '/business/sales': typeof BusinessSalesRoute
  '/business/sourcing': typeof BusinessSourcingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apply': typeof ApplyRoute
  '/business': typeof BusinessRouteWithChildren
  '/challenges': typeof ChallengesRoute
  '/friends': typeof FriendsRoute
  '/home': typeof HomeRoute
  '/job-preparation': typeof JobPreparationRoute
  '/leaderboard': typeof LeaderboardRoute
  '/location': typeof LocationRoute
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/plan': typeof PlanRoute
  '/profession': typeof ProfessionRoute
  '/profile': typeof ProfileRoute
  '/resume-analyse': typeof ResumeAnalyseRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/value-prop': typeof ValuePropRoute
  '/business/advertising': typeof BusinessAdvertisingRoute
  '/business/hiring': typeof BusinessHiringRoute
  '/business/marketing': typeof BusinessMarketingRoute
  '/business/sales': typeof BusinessSalesRoute
  '/business/sourcing': typeof BusinessSourcingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/apply': typeof ApplyRoute
  '/business': typeof BusinessRouteWithChildren
  '/challenges': typeof ChallengesRoute
  '/friends': typeof FriendsRoute
  '/home': typeof HomeRoute
  '/job-preparation': typeof JobPreparationRoute
  '/leaderboard': typeof LeaderboardRoute
  '/location': typeof LocationRoute
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/plan': typeof PlanRoute
  '/profession': typeof ProfessionRoute
  '/profile': typeof ProfileRoute
  '/resume-analyse': typeof ResumeAnalyseRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/value-prop': typeof ValuePropRoute
  '/business/advertising': typeof BusinessAdvertisingRoute
  '/business/hiring': typeof BusinessHiringRoute
  '/business/marketing': typeof BusinessMarketingRoute
  '/business/sales': typeof BusinessSalesRoute
  '/business/sourcing': typeof BusinessSourcingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/apply'
    | '/business'
    | '/challenges'
    | '/friends'
    | '/home'
    | '/job-preparation'
    | '/leaderboard'
    | '/location'
    | '/messages'
    | '/notifications'
    | '/plan'
    | '/profession'
    | '/profile'
    | '/resume-analyse'
    | '/sitemap.xml'
    | '/value-prop'
    | '/business/advertising'
    | '/business/hiring'
    | '/business/marketing'
    | '/business/sales'
    | '/business/sourcing'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/apply'
    | '/business'
    | '/challenges'
    | '/friends'
    | '/home'
    | '/job-preparation'
    | '/leaderboard'
    | '/location'
    | '/messages'
    | '/notifications'
    | '/plan'
    | '/profession'
    | '/profile'
    | '/resume-analyse'
    | '/sitemap.xml'
    | '/value-prop'
    | '/business/advertising'
    | '/business/hiring'
    | '/business/marketing'
    | '/business/sales'
    | '/business/sourcing'
  id:
    | '__root__'
    | '/'
    | '/apply'
    | '/business'
    | '/challenges'
    | '/friends'
    | '/home'
    | '/job-preparation'
    | '/leaderboard'
    | '/location'
    | '/messages'
    | '/notifications'
    | '/plan'
    | '/profession'
    | '/profile'
    | '/resume-analyse'
    | '/sitemap.xml'
    | '/value-prop'
    | '/business/advertising'
    | '/business/hiring'
    | '/business/marketing'
    | '/business/sales'
    | '/business/sourcing'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApplyRoute: typeof ApplyRoute
  BusinessRoute: typeof BusinessRouteWithChildren
  ChallengesRoute: typeof ChallengesRoute
  FriendsRoute: typeof FriendsRoute
  HomeRoute: typeof HomeRoute
  JobPreparationRoute: typeof JobPreparationRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LocationRoute: typeof LocationRoute
  MessagesRoute: typeof MessagesRoute
  NotificationsRoute: typeof NotificationsRoute
  PlanRoute: typeof PlanRoute
  ProfessionRoute: typeof ProfessionRoute
  ProfileRoute: typeof ProfileRoute
  ResumeAnalyseRoute: typeof ResumeAnalyseRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ValuePropRoute: typeof ValuePropRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business': {
      id: '/business'
      path: '/business'
      fullPath: '/business'
      preLoaderRoute: typeof BusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenges': {
      id: '/challenges'
      path: '/challenges'
      fullPath: '/challenges'
      preLoaderRoute: typeof ChallengesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/friends': {
      id: '/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof FriendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/job-preparation': {
      id: '/job-preparation'
      path: '/job-preparation'
      fullPath: '/job-preparation'
      preLoaderRoute: typeof JobPreparationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/location': {
      id: '/location'
      path: '/location'
      fullPath: '/location'
      preLoaderRoute: typeof LocationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan': {
      id: '/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof PlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profession': {
      id: '/profession'
      path: '/profession'
      fullPath: '/profession'
      preLoaderRoute: typeof ProfessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume-analyse': {
      id: '/resume-analyse'
      path: '/resume-analyse'
      fullPath: '/resume-analyse'
      preLoaderRoute: typeof ResumeAnalyseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/value-prop': {
      id: '/value-prop'
      path: '/value-prop'
      fullPath: '/value-prop'
      preLoaderRoute: typeof ValuePropRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/advertising': {
      id: '/business/advertising'
      path: '/advertising'
      fullPath: '/business/advertising'
      preLoaderRoute: typeof BusinessAdvertisingRouteImport
      parentRoute: typeof BusinessRoute
    }
    '/business/hiring': {
      id: '/business/hiring'
      path: '/hiring'
      fullPath: '/business/hiring'
      preLoaderRoute: typeof BusinessHiringRouteImport
      parentRoute: typeof BusinessRoute
    }
    '/business/marketing': {
      id: '/business/marketing'
      path: '/marketing'
      fullPath: '/business/marketing'
      preLoaderRoute: typeof BusinessMarketingRouteImport
      parentRoute: typeof BusinessRoute
    }
    '/business/sales': {
      id: '/business/sales'
      path: '/sales'
      fullPath: '/business/sales'
      preLoaderRoute: typeof BusinessSalesRouteImport
      parentRoute: typeof BusinessRoute
    }
    '/business/sourcing': {
      id: '/business/sourcing'
      path: '/sourcing'
      fullPath: '/business/sourcing'
      preLoaderRoute: typeof BusinessSourcingRouteImport
      parentRoute: typeof BusinessRoute
    }
  }
}

interface BusinessRouteChildren {
  BusinessAdvertisingRoute: typeof BusinessAdvertisingRoute
  BusinessHiringRoute: typeof BusinessHiringRoute
  BusinessMarketingRoute: typeof BusinessMarketingRoute
  BusinessSalesRoute: typeof BusinessSalesRoute
  BusinessSourcingRoute: typeof BusinessSourcingRoute
}

const BusinessRouteChildren: BusinessRouteChildren = {
  BusinessAdvertisingRoute: BusinessAdvertisingRoute,
  BusinessHiringRoute: BusinessHiringRoute,
  BusinessMarketingRoute: BusinessMarketingRoute,
  BusinessSalesRoute: BusinessSalesRoute,
  BusinessSourcingRoute: BusinessSourcingRoute,
}

const BusinessRouteWithChildren = BusinessRoute._addFileChildren(
  BusinessRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApplyRoute: ApplyRoute,
  BusinessRoute: BusinessRouteWithChildren,
  ChallengesRoute: ChallengesRoute,
  FriendsRoute: FriendsRoute,
  HomeRoute: HomeRoute,
  JobPreparationRoute: JobPreparationRoute,
  LeaderboardRoute: LeaderboardRoute,
  LocationRoute: LocationRoute,
  MessagesRoute: MessagesRoute,
  NotificationsRoute: NotificationsRoute,
  PlanRoute: PlanRoute,
  ProfessionRoute: ProfessionRoute,
  ProfileRoute: ProfileRoute,
  ResumeAnalyseRoute: ResumeAnalyseRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ValuePropRoute: ValuePropRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
