/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AppliedJobsRouteImport } from './routes/applied-jobs'
import { Route as ApplyRouteImport } from './routes/apply'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as BusinessRouteImport } from './routes/business'
import { Route as BusinessOnboardingRouteImport } from './routes/business-onboarding'
import { Route as BusinessSignupRouteImport } from './routes/business-signup'
import { Route as CareerRoadmapRouteImport } from './routes/career-roadmap'
import { Route as ChallengesRouteImport } from './routes/challenges'
import { Route as CodingInterviewRouteImport } from './routes/coding-interview'
import { Route as CollegeRouteImport } from './routes/college'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as DrivesRouteImport } from './routes/drives'
import { Route as EligibilityRouteImport } from './routes/eligibility'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FriendsRouteImport } from './routes/friends'
import { Route as HomeRouteImport } from './routes/home'
import { Route as HrInterviewRouteImport } from './routes/hr-interview'
import { Route as InterviewPracticeRouteImport } from './routes/interview-practice'
import { Route as InterviewVoiceRouteImport } from './routes/interview-voice'
import { Route as JobPreparationRouteImport } from './routes/job-preparation'
import { Route as JobRecommendationsRouteImport } from './routes/job-recommendations'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as LiveResumeRouteImport } from './routes/live-resume'
import { Route as LocationRouteImport } from './routes/location'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MentorRouteImport } from './routes/mentor'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as MyDrivesRouteImport } from './routes/my-drives'
import { Route as MyInterviewsRouteImport } from './routes/my-interviews'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as PlanRouteImport } from './routes/plan'
import { Route as ProfessionRouteImport } from './routes/profession'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ProfileDetailsRouteImport } from './routes/profile-details'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ResumeAnalyseRouteImport } from './routes/resume-analyse'
import { Route as ResumeBuilderRouteImport } from './routes/resume-builder'
import { Route as ResumeSetupRouteImport } from './routes/resume-setup'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ValuePropRouteImport } from './routes/value-prop'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminBillingRouteImport } from './routes/admin.billing'
import { Route as AdminChallengesRouteImport } from './routes/admin.challenges'
import { Route as AdminCollegesRouteImport } from './routes/admin.colleges'
import { Route as AdminCompaniesRouteImport } from './routes/admin.companies'
import { Route as AdminCoursesRouteImport } from './routes/admin.courses'
import { Route as AdminCreditsRouteImport } from './routes/admin.credits'
import { Route as AdminDrivesRouteImport } from './routes/admin.drives'
import { Route as AdminJobsRouteImport } from './routes/admin.jobs'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminPremiumRouteImport } from './routes/admin.premium'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminRoadmapsRouteImport } from './routes/admin.roadmaps'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as ApiStripeWebhookRouteImport } from './routes/api.stripe-webhook'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as BusinessAdvertisingRouteImport } from './routes/business_.advertising'
import { Route as BusinessAnalyticsRouteImport } from './routes/business_.analytics'
import { Route as BusinessApplicantsRouteImport } from './routes/business_.applicants'
import { Route as BusinessJobsRouteImport } from './routes/business_.jobs'
import { Route as BusinessMarketingRouteImport } from './routes/business_.marketing'
import { Route as BusinessNotificationsRouteImport } from './routes/business_.notifications'
import { Route as BusinessProfileRouteImport } from './routes/business_.profile'
import { Route as BusinessSalesRouteImport } from './routes/business_.sales'
import { Route as BusinessSettingsRouteImport } from './routes/business_.settings'
import { Route as BusinessSourcingRouteImport } from './routes/business_.sourcing'
import { Route as BusinessSubscriptionRouteImport } from './routes/business_.subscription'
import { Route as CCompanyIdRouteImport } from './routes/c.$companyId'
import { Route as ChallengesSlugRouteImport } from './routes/challenges.$slug'
import { Route as CheckoutCancelRouteImport } from './routes/checkout.cancel'
import { Route as CheckoutSuccessRouteImport } from './routes/checkout.success'
import { Route as CollegeDriveDriveIdRouteImport } from './routes/college-drive.$driveId'
import { Route as CoursesCourseIdRouteImport } from './routes/courses.$courseId'
import { Route as DriveDriveIdRouteImport } from './routes/drive.$driveId'
import { Route as InterviewIndexRouteImport } from './routes/interview/index'
import { Route as InterviewDeviceCheckRouteImport } from './routes/interview/device-check'
import { Route as InterviewJobDescriptionRouteImport } from './routes/interview/job-description'
import { Route as InterviewReportRouteImport } from './routes/interview/report'
import { Route as InterviewResumeUploadRouteImport } from './routes/interview/resume-upload'
import { Route as InterviewRoomRouteImport } from './routes/interview/room'
import { Route as InterviewSetupRouteImport } from './routes/interview/setup'
import { Route as UUsernameRouteImport } from './routes/u.$username'
import { Route as AnalyticsSharedTokenRouteImport } from './routes/analytics_.shared.$token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AppliedJobsRoute = AppliedJobsRouteImport.update({
  id: '/applied-jobs',
  path: '/applied-jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyRoute = ApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessRoute = BusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessOnboardingRoute = BusinessOnboardingRouteImport.update({
  id: '/business-onboarding',
  path: '/business-onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessSignupRoute = BusinessSignupRouteImport.update({
  id: '/business-signup',
  path: '/business-signup',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerRoadmapRoute = CareerRoadmapRouteImport.update({
  id: '/career-roadmap',
  path: '/career-roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengesRoute = ChallengesRouteImport.update({
  id: '/challenges',
  path: '/challenges',
  getParentRoute: () => rootRouteImport,
} as any)
const CodingInterviewRoute = CodingInterviewRouteImport.update({
  id: '/coding-interview',
  path: '/coding-interview',
  getParentRoute: () => rootRouteImport,
} as any)
const CollegeRoute = CollegeRouteImport.update({
  id: '/college',
  path: '/college',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const DrivesRoute = DrivesRouteImport.update({
  id: '/drives',
  path: '/drives',
  getParentRoute: () => rootRouteImport,
} as any)
const EligibilityRoute = EligibilityRouteImport.update({
  id: '/eligibility',
  path: '/eligibility',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FriendsRoute = FriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const HrInterviewRoute = HrInterviewRouteImport.update({
  id: '/hr-interview',
  path: '/hr-interview',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewPracticeRoute = InterviewPracticeRouteImport.update({
  id: '/interview-practice',
  path: '/interview-practice',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewVoiceRoute = InterviewVoiceRouteImport.update({
  id: '/interview-voice',
  path: '/interview-voice',
  getParentRoute: () => rootRouteImport,
} as any)
const JobPreparationRoute = JobPreparationRouteImport.update({
  id: '/job-preparation',
  path: '/job-preparation',
  getParentRoute: () => rootRouteImport,
} as any)
const JobRecommendationsRoute = JobRecommendationsRouteImport.update({
  id: '/job-recommendations',
  path: '/job-recommendations',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveResumeRoute = LiveResumeRouteImport.update({
  id: '/live-resume',
  path: '/live-resume',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationRoute = LocationRouteImport.update({
  id: '/location',
  path: '/location',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorRoute = MentorRouteImport.update({
  id: '/mentor',
  path: '/mentor',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const MyDrivesRoute = MyDrivesRouteImport.update({
  id: '/my-drives',
  path: '/my-drives',
  getParentRoute: () => rootRouteImport,
} as any)
const MyInterviewsRoute = MyInterviewsRouteImport.update({
  id: '/my-interviews',
  path: '/my-interviews',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanRoute = PlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfessionRoute = ProfessionRouteImport.update({
  id: '/profession',
  path: '/profession',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileDetailsRoute = ProfileDetailsRouteImport.update({
  id: '/profile-details',
  path: '/profile-details',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeAnalyseRoute = ResumeAnalyseRouteImport.update({
  id: '/resume-analyse',
  path: '/resume-analyse',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeBuilderRoute = ResumeBuilderRouteImport.update({
  id: '/resume-builder',
  path: '/resume-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeSetupRoute = ResumeSetupRouteImport.update({
  id: '/resume-setup',
  path: '/resume-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ValuePropRoute = ValuePropRouteImport.update({
  id: '/value-prop',
  path: '/value-prop',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBillingRoute = AdminBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AdminRoute,
} as any)
const AdminChallengesRoute = AdminChallengesRouteImport.update({
  id: '/challenges',
  path: '/challenges',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCollegesRoute = AdminCollegesRouteImport.update({
  id: '/colleges',
  path: '/colleges',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCompaniesRoute = AdminCompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCoursesRoute = AdminCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCreditsRoute = AdminCreditsRouteImport.update({
  id: '/credits',
  path: '/credits',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDrivesRoute = AdminDrivesRouteImport.update({
  id: '/drives',
  path: '/drives',
  getParentRoute: () => AdminRoute,
} as any)
const AdminJobsRoute = AdminJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPremiumRoute = AdminPremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRoadmapsRoute = AdminRoadmapsRouteImport.update({
  id: '/roadmaps',
  path: '/roadmaps',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe-webhook',
  path: '/api/stripe-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessAdvertisingRoute = BusinessAdvertisingRouteImport.update({
  id: '/business_/advertising',
  path: '/business/advertising',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessAnalyticsRoute = BusinessAnalyticsRouteImport.update({
  id: '/business_/analytics',
  path: '/business/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessApplicantsRoute = BusinessApplicantsRouteImport.update({
  id: '/business_/applicants',
  path: '/business/applicants',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessJobsRoute = BusinessJobsRouteImport.update({
  id: '/business_/jobs',
  path: '/business/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessMarketingRoute = BusinessMarketingRouteImport.update({
  id: '/business_/marketing',
  path: '/business/marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessNotificationsRoute = BusinessNotificationsRouteImport.update({
  id: '/business_/notifications',
  path: '/business/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessProfileRoute = BusinessProfileRouteImport.update({
  id: '/business_/profile',
  path: '/business/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessSalesRoute = BusinessSalesRouteImport.update({
  id: '/business_/sales',
  path: '/business/sales',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessSettingsRoute = BusinessSettingsRouteImport.update({
  id: '/business_/settings',
  path: '/business/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessSourcingRoute = BusinessSourcingRouteImport.update({
  id: '/business_/sourcing',
  path: '/business/sourcing',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessSubscriptionRoute = BusinessSubscriptionRouteImport.update({
  id: '/business_/subscription',
  path: '/business/subscription',
  getParentRoute: () => rootRouteImport,
} as any)
const CCompanyIdRoute = CCompanyIdRouteImport.update({
  id: '/c/$companyId',
  path: '/c/$companyId',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengesSlugRoute = ChallengesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ChallengesRoute,
} as any)
const CheckoutCancelRoute = CheckoutCancelRouteImport.update({
  id: '/checkout/cancel',
  path: '/checkout/cancel',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
  id: '/checkout/success',
  path: '/checkout/success',
  getParentRoute: () => rootRouteImport,
} as any)
const CollegeDriveDriveIdRoute = CollegeDriveDriveIdRouteImport.update({
  id: '/college-drive/$driveId',
  path: '/college-drive/$driveId',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesCourseIdRoute = CoursesCourseIdRouteImport.update({
  id: '/$courseId',
  path: '/$courseId',
  getParentRoute: () => CoursesRoute,
} as any)
const DriveDriveIdRoute = DriveDriveIdRouteImport.update({
  id: '/drive/$driveId',
  path: '/drive/$driveId',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewIndexRoute = InterviewIndexRouteImport.update({
  id: '/interview/',
  path: '/interview/',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewDeviceCheckRoute = InterviewDeviceCheckRouteImport.update({
  id: '/interview/device-check',
  path: '/interview/device-check',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewJobDescriptionRoute = InterviewJobDescriptionRouteImport.update({
  id: '/interview/job-description',
  path: '/interview/job-description',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewReportRoute = InterviewReportRouteImport.update({
  id: '/interview/report',
  path: '/interview/report',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewResumeUploadRoute = InterviewResumeUploadRouteImport.update({
  id: '/interview/resume-upload',
  path: '/interview/resume-upload',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewRoomRoute = InterviewRoomRouteImport.update({
  id: '/interview/room',
  path: '/interview/room',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewSetupRoute = InterviewSetupRouteImport.update({
  id: '/interview/setup',
  path: '/interview/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const UUsernameRoute = UUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsSharedTokenRoute = AnalyticsSharedTokenRouteImport.update({
  id: '/analytics_/shared/$token',
  path: '/analytics/shared/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/analytics': typeof AnalyticsRoute
  '/applied-jobs': typeof AppliedJobsRoute
  '/apply': typeof ApplyRoute
  '/billing': typeof BillingRoute
  '/business': typeof BusinessRoute
  '/business-onboarding': typeof BusinessOnboardingRoute
  '/business-signup': typeof BusinessSignupRoute
  '/career-roadmap': typeof CareerRoadmapRoute
  '/challenges': typeof ChallengesRouteWithChildren
  '/coding-interview': typeof CodingInterviewRoute
  '/college': typeof CollegeRoute
  '/courses': typeof CoursesRouteWithChildren
  '/drives': typeof DrivesRoute
  '/eligibility': typeof EligibilityRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/friends': typeof FriendsRoute
  '/home': typeof HomeRoute
  '/hr-interview': typeof HrInterviewRoute
  '/interview-practice': typeof InterviewPracticeRoute
  '/interview-voice': typeof InterviewVoiceRoute
  '/job-preparation': typeof JobPreparationRoute
  '/job-recommendations': typeof JobRecommendationsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/live-resume': typeof LiveResumeRoute
  '/location': typeof LocationRoute
  '/login': typeof LoginRoute
  '/mentor': typeof MentorRoute
  '/messages': typeof MessagesRoute
  '/my-drives': typeof MyDrivesRoute
  '/my-interviews': typeof MyInterviewsRoute
  '/notifications': typeof NotificationsRoute
  '/plan': typeof PlanRoute
  '/profession': typeof ProfessionRoute
  '/profile': typeof ProfileRoute
  '/profile-details': typeof ProfileDetailsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resume-analyse': typeof ResumeAnalyseRoute
  '/resume-builder': typeof ResumeBuilderRoute
  '/resume-setup': typeof ResumeSetupRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/value-prop': typeof ValuePropRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/challenges': typeof AdminChallengesRoute
  '/admin/colleges': typeof AdminCollegesRoute
  '/admin/companies': typeof AdminCompaniesRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/credits': typeof AdminCreditsRoute
  '/admin/drives': typeof AdminDrivesRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/premium': typeof AdminPremiumRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/roadmaps': typeof AdminRoadmapsRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/stripe-webhook': typeof ApiStripeWebhookRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/business/advertising': typeof BusinessAdvertisingRoute
  '/business/analytics': typeof BusinessAnalyticsRoute
  '/business/applicants': typeof BusinessApplicantsRoute
  '/business/jobs': typeof BusinessJobsRoute
  '/business/marketing': typeof BusinessMarketingRoute
  '/business/notifications': typeof BusinessNotificationsRoute
  '/business/profile': typeof BusinessProfileRoute
  '/business/sales': typeof BusinessSalesRoute
  '/business/settings': typeof BusinessSettingsRoute
  '/business/sourcing': typeof BusinessSourcingRoute
  '/business/subscription': typeof BusinessSubscriptionRoute
  '/c/$companyId': typeof CCompanyIdRoute
  '/challenges/$slug': typeof ChallengesSlugRoute
  '/checkout/cancel': typeof CheckoutCancelRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/college-drive/$driveId': typeof CollegeDriveDriveIdRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/drive/$driveId': typeof DriveDriveIdRoute
  '/interview/device-check': typeof InterviewDeviceCheckRoute
  '/interview/job-description': typeof InterviewJobDescriptionRoute
  '/interview/report': typeof InterviewReportRoute
  '/interview/resume-upload': typeof InterviewResumeUploadRoute
  '/interview/room': typeof InterviewRoomRoute
  '/interview/setup': typeof InterviewSetupRoute
  '/u/$username': typeof UUsernameRoute
  '/interview/': typeof InterviewIndexRoute
  '/analytics/shared/$token': typeof AnalyticsSharedTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/analytics': typeof AnalyticsRoute
  '/applied-jobs': typeof AppliedJobsRoute
  '/apply': typeof ApplyRoute
  '/billing': typeof BillingRoute
  '/business': typeof BusinessRoute
  '/business-onboarding': typeof BusinessOnboardingRoute
  '/business-signup': typeof BusinessSignupRoute
  '/career-roadmap': typeof CareerRoadmapRoute
  '/challenges': typeof ChallengesRouteWithChildren
  '/coding-interview': typeof CodingInterviewRoute
  '/college': typeof CollegeRoute
  '/courses': typeof CoursesRouteWithChildren
  '/drives': typeof DrivesRoute
  '/eligibility': typeof EligibilityRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/friends': typeof FriendsRoute
  '/home': typeof HomeRoute
  '/hr-interview': typeof HrInterviewRoute
  '/interview-practice': typeof InterviewPracticeRoute
  '/interview-voice': typeof InterviewVoiceRoute
  '/job-preparation': typeof JobPreparationRoute
  '/job-recommendations': typeof JobRecommendationsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/live-resume': typeof LiveResumeRoute
  '/location': typeof LocationRoute
  '/login': typeof LoginRoute
  '/mentor': typeof MentorRoute
  '/messages': typeof MessagesRoute
  '/my-drives': typeof MyDrivesRoute
  '/my-interviews': typeof MyInterviewsRoute
  '/notifications': typeof NotificationsRoute
  '/plan': typeof PlanRoute
  '/profession': typeof ProfessionRoute
  '/profile': typeof ProfileRoute
  '/profile-details': typeof ProfileDetailsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resume-analyse': typeof ResumeAnalyseRoute
  '/resume-builder': typeof ResumeBuilderRoute
  '/resume-setup': typeof ResumeSetupRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/value-prop': typeof ValuePropRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/challenges': typeof AdminChallengesRoute
  '/admin/colleges': typeof AdminCollegesRoute
  '/admin/companies': typeof AdminCompaniesRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/credits': typeof AdminCreditsRoute
  '/admin/drives': typeof AdminDrivesRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/premium': typeof AdminPremiumRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/roadmaps': typeof AdminRoadmapsRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/stripe-webhook': typeof ApiStripeWebhookRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/business/advertising': typeof BusinessAdvertisingRoute
  '/business/analytics': typeof BusinessAnalyticsRoute
  '/business/applicants': typeof BusinessApplicantsRoute
  '/business/jobs': typeof BusinessJobsRoute
  '/business/marketing': typeof BusinessMarketingRoute
  '/business/notifications': typeof BusinessNotificationsRoute
  '/business/profile': typeof BusinessProfileRoute
  '/business/sales': typeof BusinessSalesRoute
  '/business/settings': typeof BusinessSettingsRoute
  '/business/sourcing': typeof BusinessSourcingRoute
  '/business/subscription': typeof BusinessSubscriptionRoute
  '/c/$companyId': typeof CCompanyIdRoute
  '/challenges/$slug': typeof ChallengesSlugRoute
  '/checkout/cancel': typeof CheckoutCancelRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/college-drive/$driveId': typeof CollegeDriveDriveIdRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/drive/$driveId': typeof DriveDriveIdRoute
  '/interview/device-check': typeof InterviewDeviceCheckRoute
  '/interview/job-description': typeof InterviewJobDescriptionRoute
  '/interview/report': typeof InterviewReportRoute
  '/interview/resume-upload': typeof InterviewResumeUploadRoute
  '/interview/room': typeof InterviewRoomRoute
  '/interview/setup': typeof InterviewSetupRoute
  '/u/$username': typeof UUsernameRoute
  '/interview': typeof InterviewIndexRoute
  '/analytics/shared/$token': typeof AnalyticsSharedTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/analytics': typeof AnalyticsRoute
  '/applied-jobs': typeof AppliedJobsRoute
  '/apply': typeof ApplyRoute
  '/billing': typeof BillingRoute
  '/business': typeof BusinessRoute
  '/business-onboarding': typeof BusinessOnboardingRoute
  '/business-signup': typeof BusinessSignupRoute
  '/career-roadmap': typeof CareerRoadmapRoute
  '/challenges': typeof ChallengesRouteWithChildren
  '/coding-interview': typeof CodingInterviewRoute
  '/college': typeof CollegeRoute
  '/courses': typeof CoursesRouteWithChildren
  '/drives': typeof DrivesRoute
  '/eligibility': typeof EligibilityRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/friends': typeof FriendsRoute
  '/home': typeof HomeRoute
  '/hr-interview': typeof HrInterviewRoute
  '/interview-practice': typeof InterviewPracticeRoute
  '/interview-voice': typeof InterviewVoiceRoute
  '/job-preparation': typeof JobPreparationRoute
  '/job-recommendations': typeof JobRecommendationsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/live-resume': typeof LiveResumeRoute
  '/location': typeof LocationRoute
  '/login': typeof LoginRoute
  '/mentor': typeof MentorRoute
  '/messages': typeof MessagesRoute
  '/my-drives': typeof MyDrivesRoute
  '/my-interviews': typeof MyInterviewsRoute
  '/notifications': typeof NotificationsRoute
  '/plan': typeof PlanRoute
  '/profession': typeof ProfessionRoute
  '/profile': typeof ProfileRoute
  '/profile-details': typeof ProfileDetailsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resume-analyse': typeof ResumeAnalyseRoute
  '/resume-builder': typeof ResumeBuilderRoute
  '/resume-setup': typeof ResumeSetupRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/value-prop': typeof ValuePropRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/challenges': typeof AdminChallengesRoute
  '/admin/colleges': typeof AdminCollegesRoute
  '/admin/companies': typeof AdminCompaniesRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/credits': typeof AdminCreditsRoute
  '/admin/drives': typeof AdminDrivesRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/premium': typeof AdminPremiumRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/roadmaps': typeof AdminRoadmapsRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/stripe-webhook': typeof ApiStripeWebhookRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/business_/advertising': typeof BusinessAdvertisingRoute
  '/business_/analytics': typeof BusinessAnalyticsRoute
  '/business_/applicants': typeof BusinessApplicantsRoute
  '/business_/jobs': typeof BusinessJobsRoute
  '/business_/marketing': typeof BusinessMarketingRoute
  '/business_/notifications': typeof BusinessNotificationsRoute
  '/business_/profile': typeof BusinessProfileRoute
  '/business_/sales': typeof BusinessSalesRoute
  '/business_/settings': typeof BusinessSettingsRoute
  '/business_/sourcing': typeof BusinessSourcingRoute
  '/business_/subscription': typeof BusinessSubscriptionRoute
  '/c/$companyId': typeof CCompanyIdRoute
  '/challenges/$slug': typeof ChallengesSlugRoute
  '/checkout/cancel': typeof CheckoutCancelRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/college-drive/$driveId': typeof CollegeDriveDriveIdRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/drive/$driveId': typeof DriveDriveIdRoute
  '/interview/device-check': typeof InterviewDeviceCheckRoute
  '/interview/job-description': typeof InterviewJobDescriptionRoute
  '/interview/report': typeof InterviewReportRoute
  '/interview/resume-upload': typeof InterviewResumeUploadRoute
  '/interview/room': typeof InterviewRoomRoute
  '/interview/setup': typeof InterviewSetupRoute
  '/u/$username': typeof UUsernameRoute
  '/interview/': typeof InterviewIndexRoute
  '/analytics_/shared/$token': typeof AnalyticsSharedTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/analytics'
    | '/applied-jobs'
    | '/apply'
    | '/billing'
    | '/business'
    | '/business-onboarding'
    | '/business-signup'
    | '/career-roadmap'
    | '/challenges'
    | '/coding-interview'
    | '/college'
    | '/courses'
    | '/drives'
    | '/eligibility'
    | '/forgot-password'
    | '/friends'
    | '/home'
    | '/hr-interview'
    | '/interview-practice'
    | '/interview-voice'
    | '/job-preparation'
    | '/job-recommendations'
    | '/leaderboard'
    | '/live-resume'
    | '/location'
    | '/login'
    | '/mentor'
    | '/messages'
    | '/my-drives'
    | '/my-interviews'
    | '/notifications'
    | '/plan'
    | '/profession'
    | '/profile'
    | '/profile-details'
    | '/reset-password'
    | '/resume-analyse'
    | '/resume-builder'
    | '/resume-setup'
    | '/search'
    | '/signup'
    | '/sitemap.xml'
    | '/value-prop'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/billing'
    | '/admin/challenges'
    | '/admin/colleges'
    | '/admin/companies'
    | '/admin/courses'
    | '/admin/credits'
    | '/admin/drives'
    | '/admin/jobs'
    | '/admin/notifications'
    | '/admin/premium'
    | '/admin/reports'
    | '/admin/roadmaps'
    | '/admin/users'
    | '/api/stripe-webhook'
    | '/auth/callback'
    | '/business/advertising'
    | '/business/analytics'
    | '/business/applicants'
    | '/business/jobs'
    | '/business/marketing'
    | '/business/notifications'
    | '/business/profile'
    | '/business/sales'
    | '/business/settings'
    | '/business/sourcing'
    | '/business/subscription'
    | '/c/$companyId'
    | '/challenges/$slug'
    | '/checkout/cancel'
    | '/checkout/success'
    | '/college-drive/$driveId'
    | '/courses/$courseId'
    | '/drive/$driveId'
    | '/interview/device-check'
    | '/interview/job-description'
    | '/interview/report'
    | '/interview/resume-upload'
    | '/interview/room'
    | '/interview/setup'
    | '/u/$username'
    | '/interview/'
    | '/analytics/shared/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/analytics'
    | '/applied-jobs'
    | '/apply'
    | '/billing'
    | '/business'
    | '/business-onboarding'
    | '/business-signup'
    | '/career-roadmap'
    | '/challenges'
    | '/coding-interview'
    | '/college'
    | '/courses'
    | '/drives'
    | '/eligibility'
    | '/forgot-password'
    | '/friends'
    | '/home'
    | '/hr-interview'
    | '/interview-practice'
    | '/interview-voice'
    | '/job-preparation'
    | '/job-recommendations'
    | '/leaderboard'
    | '/live-resume'
    | '/location'
    | '/login'
    | '/mentor'
    | '/messages'
    | '/my-drives'
    | '/my-interviews'
    | '/notifications'
    | '/plan'
    | '/profession'
    | '/profile'
    | '/profile-details'
    | '/reset-password'
    | '/resume-analyse'
    | '/resume-builder'
    | '/resume-setup'
    | '/search'
    | '/signup'
    | '/sitemap.xml'
    | '/value-prop'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/billing'
    | '/admin/challenges'
    | '/admin/colleges'
    | '/admin/companies'
    | '/admin/courses'
    | '/admin/credits'
    | '/admin/drives'
    | '/admin/jobs'
    | '/admin/notifications'
    | '/admin/premium'
    | '/admin/reports'
    | '/admin/roadmaps'
    | '/admin/users'
    | '/api/stripe-webhook'
    | '/auth/callback'
    | '/business/advertising'
    | '/business/analytics'
    | '/business/applicants'
    | '/business/jobs'
    | '/business/marketing'
    | '/business/notifications'
    | '/business/profile'
    | '/business/sales'
    | '/business/settings'
    | '/business/sourcing'
    | '/business/subscription'
    | '/c/$companyId'
    | '/challenges/$slug'
    | '/checkout/cancel'
    | '/checkout/success'
    | '/college-drive/$driveId'
    | '/courses/$courseId'
    | '/drive/$driveId'
    | '/interview/device-check'
    | '/interview/job-description'
    | '/interview/report'
    | '/interview/resume-upload'
    | '/interview/room'
    | '/interview/setup'
    | '/u/$username'
    | '/interview'
    | '/analytics/shared/$token'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/analytics'
    | '/applied-jobs'
    | '/apply'
    | '/billing'
    | '/business'
    | '/business-onboarding'
    | '/business-signup'
    | '/career-roadmap'
    | '/challenges'
    | '/coding-interview'
    | '/college'
    | '/courses'
    | '/drives'
    | '/eligibility'
    | '/forgot-password'
    | '/friends'
    | '/home'
    | '/hr-interview'
    | '/interview-practice'
    | '/interview-voice'
    | '/job-preparation'
    | '/job-recommendations'
    | '/leaderboard'
    | '/live-resume'
    | '/location'
    | '/login'
    | '/mentor'
    | '/messages'
    | '/my-drives'
    | '/my-interviews'
    | '/notifications'
    | '/plan'
    | '/profession'
    | '/profile'
    | '/profile-details'
    | '/reset-password'
    | '/resume-analyse'
    | '/resume-builder'
    | '/resume-setup'
    | '/search'
    | '/signup'
    | '/sitemap.xml'
    | '/value-prop'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/billing'
    | '/admin/challenges'
    | '/admin/colleges'
    | '/admin/companies'
    | '/admin/courses'
    | '/admin/credits'
    | '/admin/drives'
    | '/admin/jobs'
    | '/admin/notifications'
    | '/admin/premium'
    | '/admin/reports'
    | '/admin/roadmaps'
    | '/admin/users'
    | '/api/stripe-webhook'
    | '/auth/callback'
    | '/business_/advertising'
    | '/business_/analytics'
    | '/business_/applicants'
    | '/business_/jobs'
    | '/business_/marketing'
    | '/business_/notifications'
    | '/business_/profile'
    | '/business_/sales'
    | '/business_/settings'
    | '/business_/sourcing'
    | '/business_/subscription'
    | '/c/$companyId'
    | '/challenges/$slug'
    | '/checkout/cancel'
    | '/checkout/success'
    | '/college-drive/$driveId'
    | '/courses/$courseId'
    | '/drive/$driveId'
    | '/interview/device-check'
    | '/interview/job-description'
    | '/interview/report'
    | '/interview/resume-upload'
    | '/interview/room'
    | '/interview/setup'
    | '/u/$username'
    | '/interview/'
    | '/analytics_/shared/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AnalyticsRoute: typeof AnalyticsRoute
  AppliedJobsRoute: typeof AppliedJobsRoute
  ApplyRoute: typeof ApplyRoute
  BillingRoute: typeof BillingRoute
  BusinessRoute: typeof BusinessRoute
  BusinessOnboardingRoute: typeof BusinessOnboardingRoute
  BusinessSignupRoute: typeof BusinessSignupRoute
  CareerRoadmapRoute: typeof CareerRoadmapRoute
  ChallengesRoute: typeof ChallengesRouteWithChildren
  CodingInterviewRoute: typeof CodingInterviewRoute
  CollegeRoute: typeof CollegeRoute
  CoursesRoute: typeof CoursesRouteWithChildren
  DrivesRoute: typeof DrivesRoute
  EligibilityRoute: typeof EligibilityRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  FriendsRoute: typeof FriendsRoute
  HomeRoute: typeof HomeRoute
  HrInterviewRoute: typeof HrInterviewRoute
  InterviewPracticeRoute: typeof InterviewPracticeRoute
  InterviewVoiceRoute: typeof InterviewVoiceRoute
  JobPreparationRoute: typeof JobPreparationRoute
  JobRecommendationsRoute: typeof JobRecommendationsRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LiveResumeRoute: typeof LiveResumeRoute
  LocationRoute: typeof LocationRoute
  LoginRoute: typeof LoginRoute
  MentorRoute: typeof MentorRoute
  MessagesRoute: typeof MessagesRoute
  MyDrivesRoute: typeof MyDrivesRoute
  MyInterviewsRoute: typeof MyInterviewsRoute
  NotificationsRoute: typeof NotificationsRoute
  PlanRoute: typeof PlanRoute
  ProfessionRoute: typeof ProfessionRoute
  ProfileRoute: typeof ProfileRoute
  ProfileDetailsRoute: typeof ProfileDetailsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ResumeAnalyseRoute: typeof ResumeAnalyseRoute
  ResumeBuilderRoute: typeof ResumeBuilderRoute
  ResumeSetupRoute: typeof ResumeSetupRoute
  SearchRoute: typeof SearchRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ValuePropRoute: typeof ValuePropRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  BusinessAdvertisingRoute: typeof BusinessAdvertisingRoute
  BusinessAnalyticsRoute: typeof BusinessAnalyticsRoute
  BusinessApplicantsRoute: typeof BusinessApplicantsRoute
  BusinessJobsRoute: typeof BusinessJobsRoute
  BusinessMarketingRoute: typeof BusinessMarketingRoute
  BusinessNotificationsRoute: typeof BusinessNotificationsRoute
  BusinessProfileRoute: typeof BusinessProfileRoute
  BusinessSalesRoute: typeof BusinessSalesRoute
  BusinessSettingsRoute: typeof BusinessSettingsRoute
  BusinessSourcingRoute: typeof BusinessSourcingRoute
  BusinessSubscriptionRoute: typeof BusinessSubscriptionRoute
  CCompanyIdRoute: typeof CCompanyIdRoute
  CheckoutCancelRoute: typeof CheckoutCancelRoute
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
  CollegeDriveDriveIdRoute: typeof CollegeDriveDriveIdRoute
  DriveDriveIdRoute: typeof DriveDriveIdRoute
  InterviewDeviceCheckRoute: typeof InterviewDeviceCheckRoute
  InterviewJobDescriptionRoute: typeof InterviewJobDescriptionRoute
  InterviewReportRoute: typeof InterviewReportRoute
  InterviewResumeUploadRoute: typeof InterviewResumeUploadRoute
  InterviewRoomRoute: typeof InterviewRoomRoute
  InterviewSetupRoute: typeof InterviewSetupRoute
  UUsernameRoute: typeof UUsernameRoute
  InterviewIndexRoute: typeof InterviewIndexRoute
  AnalyticsSharedTokenRoute: typeof AnalyticsSharedTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applied-jobs': {
      id: '/applied-jobs'
      path: '/applied-jobs'
      fullPath: '/applied-jobs'
      preLoaderRoute: typeof AppliedJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business': {
      id: '/business'
      path: '/business'
      fullPath: '/business'
      preLoaderRoute: typeof BusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business-onboarding': {
      id: '/business-onboarding'
      path: '/business-onboarding'
      fullPath: '/business-onboarding'
      preLoaderRoute: typeof BusinessOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business-signup': {
      id: '/business-signup'
      path: '/business-signup'
      fullPath: '/business-signup'
      preLoaderRoute: typeof BusinessSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career-roadmap': {
      id: '/career-roadmap'
      path: '/career-roadmap'
      fullPath: '/career-roadmap'
      preLoaderRoute: typeof CareerRoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenges': {
      id: '/challenges'
      path: '/challenges'
      fullPath: '/challenges'
      preLoaderRoute: typeof ChallengesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coding-interview': {
      id: '/coding-interview'
      path: '/coding-interview'
      fullPath: '/coding-interview'
      preLoaderRoute: typeof CodingInterviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/college': {
      id: '/college'
      path: '/college'
      fullPath: '/college'
      preLoaderRoute: typeof CollegeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drives': {
      id: '/drives'
      path: '/drives'
      fullPath: '/drives'
      preLoaderRoute: typeof DrivesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eligibility': {
      id: '/eligibility'
      path: '/eligibility'
      fullPath: '/eligibility'
      preLoaderRoute: typeof EligibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/friends': {
      id: '/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof FriendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr-interview': {
      id: '/hr-interview'
      path: '/hr-interview'
      fullPath: '/hr-interview'
      preLoaderRoute: typeof HrInterviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interview-practice': {
      id: '/interview-practice'
      path: '/interview-practice'
      fullPath: '/interview-practice'
      preLoaderRoute: typeof InterviewPracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interview-voice': {
      id: '/interview-voice'
      path: '/interview-voice'
      fullPath: '/interview-voice'
      preLoaderRoute: typeof InterviewVoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/job-preparation': {
      id: '/job-preparation'
      path: '/job-preparation'
      fullPath: '/job-preparation'
      preLoaderRoute: typeof JobPreparationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/job-recommendations': {
      id: '/job-recommendations'
      path: '/job-recommendations'
      fullPath: '/job-recommendations'
      preLoaderRoute: typeof JobRecommendationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-resume': {
      id: '/live-resume'
      path: '/live-resume'
      fullPath: '/live-resume'
      preLoaderRoute: typeof LiveResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/location': {
      id: '/location'
      path: '/location'
      fullPath: '/location'
      preLoaderRoute: typeof LocationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentor': {
      id: '/mentor'
      path: '/mentor'
      fullPath: '/mentor'
      preLoaderRoute: typeof MentorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-drives': {
      id: '/my-drives'
      path: '/my-drives'
      fullPath: '/my-drives'
      preLoaderRoute: typeof MyDrivesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-interviews': {
      id: '/my-interviews'
      path: '/my-interviews'
      fullPath: '/my-interviews'
      preLoaderRoute: typeof MyInterviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan': {
      id: '/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof PlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profession': {
      id: '/profession'
      path: '/profession'
      fullPath: '/profession'
      preLoaderRoute: typeof ProfessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile-details': {
      id: '/profile-details'
      path: '/profile-details'
      fullPath: '/profile-details'
      preLoaderRoute: typeof ProfileDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume-analyse': {
      id: '/resume-analyse'
      path: '/resume-analyse'
      fullPath: '/resume-analyse'
      preLoaderRoute: typeof ResumeAnalyseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume-builder': {
      id: '/resume-builder'
      path: '/resume-builder'
      fullPath: '/resume-builder'
      preLoaderRoute: typeof ResumeBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume-setup': {
      id: '/resume-setup'
      path: '/resume-setup'
      fullPath: '/resume-setup'
      preLoaderRoute: typeof ResumeSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/value-prop': {
      id: '/value-prop'
      path: '/value-prop'
      fullPath: '/value-prop'
      preLoaderRoute: typeof ValuePropRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/billing': {
      id: '/admin/billing'
      path: '/billing'
      fullPath: '/admin/billing'
      preLoaderRoute: typeof AdminBillingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/challenges': {
      id: '/admin/challenges'
      path: '/challenges'
      fullPath: '/admin/challenges'
      preLoaderRoute: typeof AdminChallengesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/colleges': {
      id: '/admin/colleges'
      path: '/colleges'
      fullPath: '/admin/colleges'
      preLoaderRoute: typeof AdminCollegesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/companies': {
      id: '/admin/companies'
      path: '/companies'
      fullPath: '/admin/companies'
      preLoaderRoute: typeof AdminCompaniesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/courses': {
      id: '/admin/courses'
      path: '/courses'
      fullPath: '/admin/courses'
      preLoaderRoute: typeof AdminCoursesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/credits': {
      id: '/admin/credits'
      path: '/credits'
      fullPath: '/admin/credits'
      preLoaderRoute: typeof AdminCreditsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/drives': {
      id: '/admin/drives'
      path: '/drives'
      fullPath: '/admin/drives'
      preLoaderRoute: typeof AdminDrivesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/jobs': {
      id: '/admin/jobs'
      path: '/jobs'
      fullPath: '/admin/jobs'
      preLoaderRoute: typeof AdminJobsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/premium': {
      id: '/admin/premium'
      path: '/premium'
      fullPath: '/admin/premium'
      preLoaderRoute: typeof AdminPremiumRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/roadmaps': {
      id: '/admin/roadmaps'
      path: '/roadmaps'
      fullPath: '/admin/roadmaps'
      preLoaderRoute: typeof AdminRoadmapsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/stripe-webhook': {
      id: '/api/stripe-webhook'
      path: '/api/stripe-webhook'
      fullPath: '/api/stripe-webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business_/advertising': {
      id: '/business_/advertising'
      path: '/business/advertising'
      fullPath: '/business/advertising'
      preLoaderRoute: typeof BusinessAdvertisingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business_/analytics': {
      id: '/business_/analytics'
      path: '/business/analytics'
      fullPath: '/business/analytics'
      preLoaderRoute: typeof BusinessAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business_/applicants': {
      id: '/business_/applicants'
      path: '/business/applicants'
      fullPath: '/business/applicants'
      preLoaderRoute: typeof BusinessApplicantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business_/jobs': {
      id: '/business_/jobs'
      path: '/business/jobs'
      fullPath: '/business/jobs'
      preLoaderRoute: typeof BusinessJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business_/marketing': {
      id: '/business_/marketing'
      path: '/business/marketing'
      fullPath: '/business/marketing'
      preLoaderRoute: typeof BusinessMarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business_/notifications': {
      id: '/business_/notifications'
      path: '/business/notifications'
      fullPath: '/business/notifications'
      preLoaderRoute: typeof BusinessNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business_/profile': {
      id: '/business_/profile'
      path: '/business/profile'
      fullPath: '/business/profile'
      preLoaderRoute: typeof BusinessProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business_/sales': {
      id: '/business_/sales'
      path: '/business/sales'
      fullPath: '/business/sales'
      preLoaderRoute: typeof BusinessSalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business_/settings': {
      id: '/business_/settings'
      path: '/business/settings'
      fullPath: '/business/settings'
      preLoaderRoute: typeof BusinessSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business_/sourcing': {
      id: '/business_/sourcing'
      path: '/business/sourcing'
      fullPath: '/business/sourcing'
      preLoaderRoute: typeof BusinessSourcingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business_/subscription': {
      id: '/business_/subscription'
      path: '/business/subscription'
      fullPath: '/business/subscription'
      preLoaderRoute: typeof BusinessSubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$companyId': {
      id: '/c/$companyId'
      path: '/c/$companyId'
      fullPath: '/c/$companyId'
      preLoaderRoute: typeof CCompanyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenges/$slug': {
      id: '/challenges/$slug'
      path: '/$slug'
      fullPath: '/challenges/$slug'
      preLoaderRoute: typeof ChallengesSlugRouteImport
      parentRoute: typeof ChallengesRoute
    }
    '/checkout/cancel': {
      id: '/checkout/cancel'
      path: '/checkout/cancel'
      fullPath: '/checkout/cancel'
      preLoaderRoute: typeof CheckoutCancelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/success': {
      id: '/checkout/success'
      path: '/checkout/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof CheckoutSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/college-drive/$driveId': {
      id: '/college-drive/$driveId'
      path: '/college-drive/$driveId'
      fullPath: '/college-drive/$driveId'
      preLoaderRoute: typeof CollegeDriveDriveIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$courseId': {
      id: '/courses/$courseId'
      path: '/$courseId'
      fullPath: '/courses/$courseId'
      preLoaderRoute: typeof CoursesCourseIdRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/drive/$driveId': {
      id: '/drive/$driveId'
      path: '/drive/$driveId'
      fullPath: '/drive/$driveId'
      preLoaderRoute: typeof DriveDriveIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interview/': {
      id: '/interview/'
      path: '/interview'
      fullPath: '/interview/'
      preLoaderRoute: typeof InterviewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interview/device-check': {
      id: '/interview/device-check'
      path: '/interview/device-check'
      fullPath: '/interview/device-check'
      preLoaderRoute: typeof InterviewDeviceCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interview/job-description': {
      id: '/interview/job-description'
      path: '/interview/job-description'
      fullPath: '/interview/job-description'
      preLoaderRoute: typeof InterviewJobDescriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interview/report': {
      id: '/interview/report'
      path: '/interview/report'
      fullPath: '/interview/report'
      preLoaderRoute: typeof InterviewReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interview/resume-upload': {
      id: '/interview/resume-upload'
      path: '/interview/resume-upload'
      fullPath: '/interview/resume-upload'
      preLoaderRoute: typeof InterviewResumeUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interview/room': {
      id: '/interview/room'
      path: '/interview/room'
      fullPath: '/interview/room'
      preLoaderRoute: typeof InterviewRoomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interview/setup': {
      id: '/interview/setup'
      path: '/interview/setup'
      fullPath: '/interview/setup'
      preLoaderRoute: typeof InterviewSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics_/shared/$token': {
      id: '/analytics_/shared/$token'
      path: '/analytics/shared/$token'
      fullPath: '/analytics/shared/$token'
      preLoaderRoute: typeof AnalyticsSharedTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminBillingRoute: typeof AdminBillingRoute
  AdminChallengesRoute: typeof AdminChallengesRoute
  AdminCollegesRoute: typeof AdminCollegesRoute
  AdminCompaniesRoute: typeof AdminCompaniesRoute
  AdminCoursesRoute: typeof AdminCoursesRoute
  AdminCreditsRoute: typeof AdminCreditsRoute
  AdminDrivesRoute: typeof AdminDrivesRoute
  AdminJobsRoute: typeof AdminJobsRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminPremiumRoute: typeof AdminPremiumRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminRoadmapsRoute: typeof AdminRoadmapsRoute
  AdminUsersRoute: typeof AdminUsersRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminBillingRoute: AdminBillingRoute,
  AdminChallengesRoute: AdminChallengesRoute,
  AdminCollegesRoute: AdminCollegesRoute,
  AdminCompaniesRoute: AdminCompaniesRoute,
  AdminCoursesRoute: AdminCoursesRoute,
  AdminCreditsRoute: AdminCreditsRoute,
  AdminDrivesRoute: AdminDrivesRoute,
  AdminJobsRoute: AdminJobsRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminPremiumRoute: AdminPremiumRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminRoadmapsRoute: AdminRoadmapsRoute,
  AdminUsersRoute: AdminUsersRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ChallengesRouteChildren {
  ChallengesSlugRoute: typeof ChallengesSlugRoute
}

const ChallengesRouteChildren: ChallengesRouteChildren = {
  ChallengesSlugRoute: ChallengesSlugRoute,
}

const ChallengesRouteWithChildren = ChallengesRoute._addFileChildren(
  ChallengesRouteChildren,
)

interface CoursesRouteChildren {
  CoursesCourseIdRoute: typeof CoursesCourseIdRoute
}

const CoursesRouteChildren: CoursesRouteChildren = {
  CoursesCourseIdRoute: CoursesCourseIdRoute,
}

const CoursesRouteWithChildren =
  CoursesRoute._addFileChildren(CoursesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AnalyticsRoute: AnalyticsRoute,
  AppliedJobsRoute: AppliedJobsRoute,
  ApplyRoute: ApplyRoute,
  BillingRoute: BillingRoute,
  BusinessRoute: BusinessRoute,
  BusinessOnboardingRoute: BusinessOnboardingRoute,
  BusinessSignupRoute: BusinessSignupRoute,
  CareerRoadmapRoute: CareerRoadmapRoute,
  ChallengesRoute: ChallengesRouteWithChildren,
  CodingInterviewRoute: CodingInterviewRoute,
  CollegeRoute: CollegeRoute,
  CoursesRoute: CoursesRouteWithChildren,
  DrivesRoute: DrivesRoute,
  EligibilityRoute: EligibilityRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  FriendsRoute: FriendsRoute,
  HomeRoute: HomeRoute,
  HrInterviewRoute: HrInterviewRoute,
  InterviewPracticeRoute: InterviewPracticeRoute,
  InterviewVoiceRoute: InterviewVoiceRoute,
  JobPreparationRoute: JobPreparationRoute,
  JobRecommendationsRoute: JobRecommendationsRoute,
  LeaderboardRoute: LeaderboardRoute,
  LiveResumeRoute: LiveResumeRoute,
  LocationRoute: LocationRoute,
  LoginRoute: LoginRoute,
  MentorRoute: MentorRoute,
  MessagesRoute: MessagesRoute,
  MyDrivesRoute: MyDrivesRoute,
  MyInterviewsRoute: MyInterviewsRoute,
  NotificationsRoute: NotificationsRoute,
  PlanRoute: PlanRoute,
  ProfessionRoute: ProfessionRoute,
  ProfileRoute: ProfileRoute,
  ProfileDetailsRoute: ProfileDetailsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ResumeAnalyseRoute: ResumeAnalyseRoute,
  ResumeBuilderRoute: ResumeBuilderRoute,
  ResumeSetupRoute: ResumeSetupRoute,
  SearchRoute: SearchRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ValuePropRoute: ValuePropRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  BusinessAdvertisingRoute: BusinessAdvertisingRoute,
  BusinessAnalyticsRoute: BusinessAnalyticsRoute,
  BusinessApplicantsRoute: BusinessApplicantsRoute,
  BusinessJobsRoute: BusinessJobsRoute,
  BusinessMarketingRoute: BusinessMarketingRoute,
  BusinessNotificationsRoute: BusinessNotificationsRoute,
  BusinessProfileRoute: BusinessProfileRoute,
  BusinessSalesRoute: BusinessSalesRoute,
  BusinessSettingsRoute: BusinessSettingsRoute,
  BusinessSourcingRoute: BusinessSourcingRoute,
  BusinessSubscriptionRoute: BusinessSubscriptionRoute,
  CCompanyIdRoute: CCompanyIdRoute,
  CheckoutCancelRoute: CheckoutCancelRoute,
  CheckoutSuccessRoute: CheckoutSuccessRoute,
  CollegeDriveDriveIdRoute: CollegeDriveDriveIdRoute,
  DriveDriveIdRoute: DriveDriveIdRoute,
  InterviewDeviceCheckRoute: InterviewDeviceCheckRoute,
  InterviewJobDescriptionRoute: InterviewJobDescriptionRoute,
  InterviewReportRoute: InterviewReportRoute,
  InterviewResumeUploadRoute: InterviewResumeUploadRoute,
  InterviewRoomRoute: InterviewRoomRoute,
  InterviewSetupRoute: InterviewSetupRoute,
  UUsernameRoute: UUsernameRoute,
  InterviewIndexRoute: InterviewIndexRoute,
  AnalyticsSharedTokenRoute: AnalyticsSharedTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
