-- =====================================================================
-- Seed real, verified problems for the 17 remaining empty topics: java,
-- go, cpp, typescript, nodejs, express, nextjs, aws, docker, kubernetes,
-- devops, databases, rest-apis, machine-learning, data-science,
-- artificial-intelligence (cybersecurity + c++-adjacent covered where
-- listed). Every expected_output was generated by running a reference
-- solver against the stated input (see the migration's companion script
-- used to derive these — not hand-guessed), 3 problems per topic.
-- =====================================================================

-- ---------------------------------------------------------------------
-- JAVA
-- ---------------------------------------------------------------------
insert into challenges (title, slug, description, difficulty, category_id, estimated_minutes, xp_reward, tags, constraints, input_format, output_format, starter_code)
values (
  'Reverse Integer',
  'java-reverse-integer',
  'Reverse the digits of a 32-bit signed integer. If reversing causes the value to fall outside the 32-bit signed range [-2^31, 2^31 - 1], output 0 instead.',
  'medium',
  (select id from challenge_categories where slug = 'java'),
  20, 50,
  array['java', 'math'],
  '-2^31 <= x <= 2^31 - 1',
  'A single integer: x.',
  'A single integer: the reversed value, or 0 on overflow.',
  $sc${"java":"import java.util.*;\npublic class Main {\n  public static void main(String[] args) {\n    Scanner sc = new Scanner(System.in);\n    long x = sc.nextLong();\n    // TODO: reverse digits, return 0 on 32-bit overflow\n    System.out.println(0);\n  }\n}\n","python":"x = int(input())\n# TODO: reverse digits, return 0 on 32-bit overflow\nprint(0)\n"}$sc$::jsonb
) on conflict (slug) do nothing;

insert into challenges (title, slug, description, difficulty, category_id, estimated_minutes, xp_reward, tags, constraints, input_format, output_format, starter_code)
values (
  'Palindrome Number',
  'java-palindrome-number',
  'Determine whether an integer is a palindrome when written in base 10 (negative numbers are never palindromes).',
  'easy',
  (select id from challenge_categories where slug = 'java'),
  10, 20,
  array['java', 'math'],
  '-2^31 <= x <= 2^31 - 1',
  'A single integer: x.',
  '"true" or "false".',
  $sc${"java":"import java.util.*;\npublic class Main {\n  public static void main(String[] args) {\n    Scanner sc = new Scanner(System.in);\n    long x = sc.nextLong();\n    // TODO\n    System.out.println(\"false\");\n  }\n}\n","python":"x = int(input())\n# TODO\nprint('false')\n"}$sc$::jsonb
) on conflict (slug) do nothing;

insert into challenges (title, slug, description, difficulty, category_id, estimated_minutes, xp_reward, tags, constraints, input_format, output_format, starter_code)
values (
  'Count Set Bits',
  'java-count-set-bits',
  'Given a non-negative integer n, count how many bits are set to 1 in its binary representation.',
  'easy',
  (select id from challenge_categories where slug = 'java'),
  10, 20,
  array['java', 'bit-manipulation'],
  '0 <= n <= 10^9',
  'A single integer: n.',
  'A single integer: the number of set bits.',
  $sc${"java":"import java.util.*;\npublic class Main {\n  public static void main(String[] args) {\n    Scanner sc = new Scanner(System.in);\n    long n = sc.nextLong();\n    // TODO\n    System.out.println(0);\n  }\n}\n","python":"n = int(input())\n# TODO\nprint(0)\n"}$sc$::jsonb
) on conflict (slug) do nothing;

insert into challenge_test_cases (challenge_id, input, expected_output, is_hidden)
select c.id, v.input, v.expected_output, v.is_hidden from challenges c cross join (values
  ($i$123$i$, $o$321$o$, false), ($i$-123$i$, $o$-321$o$, true), ($i$120$i$, $o$21$o$, true), ($i$1534236469$i$, $o$0$o$, true)
) as v(input, expected_output, is_hidden)
where c.slug = 'java-reverse-integer' and not exists (select 1 from challenge_test_cases tc where tc.challenge_id = c.id);

insert into challenge_test_cases (challenge_id, input, expected_output, is_hidden)
select c.id, v.input, v.expected_output, v.is_hidden from challenges c cross join (values
  ($i$121$i$, $o$true$o$, false), ($i$-121$i$, $o$false$o$, true), ($i$10$i$, $o$false$o$, true)
) as v(input, expected_output, is_hidden)
where c.slug = 'java-palindrome-number' and not exists (select 1 from challenge_test_cases tc where tc.challenge_id = c.id);

insert into challenge_test_cases (challenge_id, input, expected_output, is_hidden)
select c.id, v.input, v.expected_output, v.is_hidden from challenges c cross join (values
  ($i$11$i$, $o$3$o$, false), ($i$128$i$, $o$1$o$, true), ($i$255$i$, $o$8$o$, true)
) as v(input, expected_output, is_hidden)
where c.slug = 'java-count-set-bits' and not exists (select 1 from challenge_test_cases tc where tc.challenge_id = c.id);

-- ---------------------------------------------------------------------
-- GO
-- ---------------------------------------------------------------------
insert into challenges (title, slug, description, difficulty, category_id, estimated_minutes, xp_reward, tags, constraints, input_format, output_format, starter_code)
values (
  'FizzBuzz Sum',
  'go-fizzbuzz-sum',
  'Given n, sum all integers from 1 to n (inclusive) that are divisible by 3 or 5.',
  'easy',
  (select id from challenge_categories where slug = 'go'),
  10, 20,
  array['go', 'math'],
  '1 <= n <= 1000000',
  'A single integer: n.',
  'A single integer: the sum.',
  $sc${"go":"package main\nimport \"fmt\"\nfunc main() {\n  var n int\n  fmt.Scan(&n)\n  // TODO: sum multiples of 3 or 5 up to n\n  fmt.Println(0)\n}\n","python":"n = int(input())\n# TODO\nprint(0)\n"}$sc$::jsonb
) on conflict (slug) do nothing;

insert into challenges (title, slug, description, difficulty, category_id, estimated_minutes, xp_reward, tags, constraints, input_format, output_format, starter_code)
values (
  'Find the Missing Number',
  'go-missing-number',
  'An array contains n distinct numbers taken from the range 0..n (so exactly one number in that range is missing). Find it.',
  'easy',
  (select id from challenge_categories where slug = 'go'),
  15, 20,
  array['go', 'arrays', 'math'],
  '1 <= n <= 100000',
  'Line 1: n. Line 2: n space-separated integers.',
  'A single integer: the missing number.',
  $sc${"go":"package main\nimport \"fmt\"\nfunc main() {\n  var n int\n  fmt.Scan(&n)\n  arr := make([]int, n)\n  for i := range arr { fmt.Scan(&arr[i]) }\n  // TODO: expected sum (0..n) minus actual sum\n  fmt.Println(0)\n}\n","python":"n = int(input())\narr = list(map(int, input().split()))\n# TODO\nprint(0)\n"}$sc$::jsonb
) on conflict (slug) do nothing;

insert into challenges (title, slug, description, difficulty, category_id, estimated_minutes, xp_reward, tags, constraints, input_format, output_format, starter_code)
values (
  'Maximum Subarray Sum (Kadane)',
  'go-max-subarray-kadane',
  'Given an array of integers (may include negatives), find the maximum sum of any contiguous subarray using Kadane''s algorithm.',
  'medium',
  (select id from challenge_categories where slug = 'go'),
  20, 50,
  array['go', 'dynamic-programming', 'arrays'],
  '1 <= n <= 100000',
  'Line 1: n. Line 2: n space-separated integers.',
  'A single integer: the maximum subarray sum.',
  $sc${"go":"package main\nimport \"fmt\"\nfunc main() {\n  var n int\n  fmt.Scan(&n)\n  arr := make([]int, n)\n  for i := range arr { fmt.Scan(&arr[i]) }\n  // TODO: Kadane's algorithm\n  fmt.Println(0)\n}\n","python":"n = int(input())\narr = list(map(int, input().split()))\n# TODO: Kadane's algorithm\nprint(0)\n"}$sc$::jsonb
) on conflict (slug) do nothing;

insert into challenge_test_cases (challenge_id, input, expected_output, is_hidden)
select c.id, v.input, v.expected_output, v.is_hidden from challenges c cross join (values
  ($i$10$i$, $o$33$o$, false), ($i$20$i$, $o$98$o$, true)
) as v(input, expected_output, is_hidden)
where c.slug = 'go-fizzbuzz-sum' and not exists (select 1 from challenge_test_cases tc where tc.challenge_id = c.id);

insert into challenge_test_cases (challenge_id, input, expected_output, is_hidden)
select c.id, v.input, v.expected_output, v.is_hidden from challenges c cross join (values
  ($i$3
3 0 1$i$, $o$2$o$, false),
  ($i$2
0 1$i$, $o$2$o$, true)
) as v(input, expected_output, is_hidden)
where c.slug = 'go-missing-number' and not exists (select 1 from challenge_test_cases tc where tc.challenge_id = c.id);

insert into challenge_test_cases (challenge_id, input, expected_output, is_hidden)
select c.id, v.input, v.expected_output, v.is_hidden from challenges c cross join (values
  ($i$9
-2 1 -3 4 -1 2 1 -5 4$i$, $o$6$o$, false),
  ($i$1
1$i$, $o$1$o$, true),
  ($i$3
-1 -2 -3$i$, $o$-1$o$, true)
) as v(input, expected_output, is_hidden)
where c.slug = 'go-max-subarray-kadane' and not exists (select 1 from challenge_test_cases tc where tc.challenge_id = c.id);

-- ---------------------------------------------------------------------
-- C++
-- ---------------------------------------------------------------------
insert into challenges (title, slug, description, difficulty, category_id, estimated_minutes, xp_reward, tags, constraints, input_format, output_format, starter_code)
values (
  'Integer Power',
  'cpp-power',
  'Compute x raised to the power n (n >= 0) using fast exponentiation.',
  'easy',
  (select id from challenge_categories where slug = 'cpp'),
  15, 20,
  array['cpp', 'math'],
  '1 <= x <= 10, 0 <= n <= 30',
  'Two space-separated integers: x n.',
  'A single integer: x^n.',
  $sc${"cpp":"#include <iostream>\nusing namespace std;\nint main() {\n  long long x, n;\n  cin >> x >> n;\n  // TODO: fast exponentiation\n  cout << 0 << endl;\n}\n","python":"x, n = map(int, input().split())\n# TODO\nprint(0)\n"}$sc$::jsonb
) on conflict (slug) do nothing;

insert into challenges (title, slug, description, difficulty, category_id, estimated_minutes, xp_reward, tags, constraints, input_format, output_format, starter_code)
values (
  'GCD and LCM',
  'cpp-gcd-lcm',
  'Given two positive integers a and b, output their GCD and LCM (space-separated).',
  'easy',
  (select id from challenge_categories where slug = 'cpp'),
  15, 20,
  array['cpp', 'math'],
  '1 <= a, b <= 10^9',
  'Two space-separated integers: a b.',
  'Two space-separated integers: gcd lcm.',
  $sc${"cpp":"#include <iostream>\nusing namespace std;\nint main() {\n  long long a, b;\n  cin >> a >> b;\n  // TODO: Euclidean algorithm for gcd, then lcm = a*b/gcd\n  cout << 0 << \" \" << 0 << endl;\n}\n","python":"a, b = map(int, input().split())\n# TODO\nprint(0, 0)\n"}$sc$::jsonb
) on conflict (slug) do nothing;

insert into challenges (title, slug, description, difficulty, category_id, estimated_minutes, xp_reward, tags, constraints, input_format, output_format, starter_code)
values (
  'Digital Root',
  'cpp-digital-root',
  'Given a non-negative integer n, repeatedly sum its digits until a single digit remains (the digital root).',
  'easy',
  (select id from challenge_categories where slug = 'cpp'),
  10, 20,
  array['cpp', 'math'],
  '0 <= n <= 10^18',
  'A single integer: n.',
  'A single integer: the digital root.',
  $sc${"cpp":"#include <iostream>\nusing namespace std;\nint main() {\n  long long n;\n  cin >> n;\n  // TODO: digital root formula (0 if n==0, else 1 + (n-1) % 9)\n  cout << 0 << endl;\n}\n","python":"n = int(input())\n# TODO\nprint(0)\n"}$sc$::jsonb
) on conflict (slug) do nothing;

insert into challenge_test_cases (challenge_id, input, expected_output, is_hidden)
select c.id, v.input, v.expected_output, v.is_hidden from challenges c cross join (values
  ($i$2 10$i$, $o$1024$o$, false), ($i$3 0$i$, $o$1$o$, true)
) as v(input, expected_output, is_hidden)
where c.slug = 'cpp-power' and not exists (select 1 from challenge_test_cases tc where tc.challenge_id = c.id);

insert into challenge_test_cases (challenge_id, input, expected_output, is_hidden)
select c.id, v.input, v.expected_output, v.is_hidden from challenges c cross join (values
  ($i$12 18$i$, $o$6 36$o$, false), ($i$7 13$i$, $o$1 91$o$, true)
) as v(input, expected_output, is_hidden)
where c.slug = 'cpp-gcd-lcm' and not exists (select 1 from challenge_test_cases tc where tc.challenge_id = c.id);

insert into challenge_test_cases (challenge_id, input, expected_output, is_hidden)
select c.id, v.input, v.expected_output, v.is_hidden from challenges c cross join (values
  ($i$942$i$, $o$6$o$, false), ($i$132$i$, $o$6$o$, true), ($i$0$i$, $o$0$o$, true)
) as v(input, expected_output, is_hidden)
where c.slug = 'cpp-digital-root' and not exists (select 1 from challenge_test_cases tc where tc.challenge_id = c.id);

-- ---------------------------------------------------------------------
-- TYPESCRIPT
-- ---------------------------------------------------------------------
insert into challenges (title, slug, description, difficulty, category_id, estimated_minutes, xp_reward, tags, constraints, input_format, output_format, starter_code)
values (
  'Route Param Extraction',
  'ts-route-param-extract',
  'Given a route pattern with :param segments (as commonly typed in a TS router) and an actual URL, extract each parameter''s value in the order the params appear in the pattern.',
  'easy',
  (select id from challenge_categories where slug = 'typescript'),
  15, 20,
  array['typescript', 'strings'],
  'Pattern and URL always have the same number of segments.',
  'Line 1: the route pattern. Line 2: the actual URL.',
  'Space-separated "name=value" pairs, in pattern order.',
  $sc${"javascript":"const [pattern, url] = require('fs').readFileSync(0, 'utf8').trim().split('\\n');\n// TODO: split both by '/', match ':name' segments to url segments\nconsole.log('');\n","typescript":"const [pattern, url] = require('fs').readFileSync(0, 'utf8').trim().split('\\n');\n// TODO: split both by '/', match ':name' segments to url segments\nconsole.log('');\n"}$sc$::jsonb
) on conflict (slug) do nothing;

insert into challenges (title, slug, description, difficulty, category_id, estimated_minutes, xp_reward, tags, constraints, input_format, output_format, starter_code)
values (
  'Discriminated Union Area Sum',
  'ts-shape-area-sum',
  'Given n shapes, each either "square s" or "rectangle w h", sum the floor of each shape''s area (classic TypeScript discriminated-union modeling exercise).',
  'easy',
  (select id from challenge_categories where slug = 'typescript'),
  15, 20,
  array['typescript', 'math'],
  '1 <= n <= 1000',
  'Line 1: n. Next n lines: "square s" or "rectangle w h".',
  'A single integer: the total area.',
  $sc${"javascript":"const lines = require('fs').readFileSync(0, 'utf8').trim().split('\\n');\nconst n = Number(lines[0]);\n// TODO: sum floor(area) for each shape\nconsole.log(0);\n","typescript":"const lines = require('fs').readFileSync(0, 'utf8').trim().split('\\n');\nconst n = Number(lines[0]);\n// TODO: sum floor(area) for each shape\nconsole.log(0);\n"}$sc$::jsonb
) on conflict (slug) do nothing;

insert into challenges (title, slug, description, difficulty, category_id, estimated_minutes, xp_reward, tags, constraints, input_format, output_format, starter_code)
values (
  'Generic Stack Max Tracker',
  'ts-stack-max',
  'Simulate a stack of numbers given a sequence of "PUSH x" / "POP" operations, then output the maximum value that was ever present on the stack.',
  'easy',
  (select id from challenge_categories where slug = 'typescript'),
  15, 20,
  array['typescript', 'stacks'],
  '1 <= number of operations <= 10000',
  'One operation per line: "PUSH x" or "POP".',
  'A single integer: the maximum value ever pushed.',
  $sc${"javascript":"const lines = require('fs').readFileSync(0, 'utf8').trim().split('\\n');\n// TODO: track max across all PUSH values\nconsole.log(0);\n","typescript":"const lines = require('fs').readFileSync(0, 'utf8').trim().split('\\n');\n// TODO: track max across all PUSH values\nconsole.log(0);\n"}$sc$::jsonb
) on conflict (slug) do nothing;

insert into challenge_test_cases (challenge_id, input, expected_output, is_hidden)
select c.id, v.input, v.expected_output, v.is_hidden from challenges c cross join (values
  ($i$/users/:id/posts/:postId
/users/42/posts/7$i$, $o$id=42 postId=7$o$, false),
  ($i$/a/:x
/a/99$i$, $o$x=99$o$, true)
) as v(input, expected_output, is_hidden)
where c.slug = 'ts-route-param-extract' and not exists (select 1 from challenge_test_cases tc where tc.challenge_id = c.id);

insert into challenge_test_cases (challenge_id, input, expected_output, is_hidden)
select c.id, v.input, v.expected_output, v.is_hidden from challenges c cross join (values
  ($i$2
rectangle 4 5
square 3$i$, $o$29$o$, false),
  ($i$2
square 5
rectangle 2 3$i$, $o$31$o$, true)
) as v(input, expected_output, is_hidden)
where c.slug = 'ts-shape-area-sum' and not exists (select 1 from challenge_test_cases tc where tc.challenge_id = c.id);

insert into challenge_test_cases (challenge_id, input, expected_output, is_hidden)
select c.id, v.input, v.expected_output, v.is_hidden from challenges c cross join (values
  ($i$PUSH 3
PUSH 7
POP
PUSH 2$i$, $o$7$o$, false),
  ($i$PUSH 5
PUSH 1
POP
POP$i$, $o$5$o$, true)
) as v(input, expected_output, is_hidden)
where c.slug = 'ts-stack-max' and not exists (select 1 from challenge_test_cases tc where tc.challenge_id = c.id);

-- ---------------------------------------------------------------------
-- NODE.JS
-- ---------------------------------------------------------------------
insert into challenges (title, slug, description, difficulty, category_id, estimated_minutes, xp_reward, tags, constraints, input_format, output_format, starter_code)
values (
  'Event Loop Execution Order',
  'node-event-loop-order',
  'Given a list of operations — "SYNC label", "PROMISE label" (microtask), or "TIMEOUT label ms" (macrotask) — output the labels in the order Node.js would actually execute them: all synchronous code first (in code order), then all resolved promises/microtasks (in code order), then timers (ordered by delay, ties by code order).',
  'medium',
  (select id from challenge_categories where slug = 'nodejs'),
  20, 50,
  array['nodejs', 'event-loop'],
  '1 <= number of operations <= 1000',
  'One operation per line.',
  'Space-separated labels in execution order.',
  $sc${"javascript":"const lines = require('fs').readFileSync(0, 'utf8').trim().split('\\n');\n// TODO: bucket into sync / microtask / macrotask (sorted by ms) and concatenate\nconsole.log('');\n"}$sc$::jsonb
) on conflict (slug) do nothing;

insert into challenges (title, slug, description, difficulty, category_id, estimated_minutes, xp_reward, tags, constraints, input_format, output_format, starter_code)
values (
  'Debounce Fire Count',
  'node-debounce-fires',
  'A debounced function only fires `wait` ms after the last call in a burst. Given a sorted list of call timestamps and the wait duration, output how many times the debounced function actually fires.',
  'medium',
  (select id from challenge_categories where slug = 'nodejs'),
  20, 50,
  array['nodejs', 'timing'],
  '1 <= number of calls <= 10000',
  'Line 1: space-separated call timestamps (ms, sorted ascending). Line 2: wait (ms).',
  'A single integer: number of times the debounced function fires.',
  $sc${"javascript":"const lines = require('fs').readFileSync(0, 'utf8').trim().split('\\n');\nconst calls = lines[0].trim().split(' ').map(Number);\nconst wait = Number(lines[1].trim());\n// TODO: a new burst (and thus a new fire) starts whenever the gap since the previous call exceeds wait\nconsole.log(0);\n"}$sc$::jsonb
) on conflict (slug) do nothing;

insert into challenges (title, slug, description, difficulty, category_id, estimated_minutes, xp_reward, tags, constraints, input_format, output_format, starter_code)
values (
  'Middleware Chain Execution',
  'node-middleware-chain',
  'Given n middleware functions, each either calling next() (1) or not (0), determine which 0-based indices actually execute — execution stops at (and includes) the first middleware that does not call next().',
  'easy',
  (select id from challenge_categories where slug = 'nodejs'),
  15, 20,
  array['nodejs', 'middleware'],
  '1 <= n <= 10000',
  'n space-separated 0/1 values.',
  'Space-separated indices that execute.',
  $sc${"javascript":"const arr = require('fs').readFileSync(0, 'utf8').trim().split(' ').map(Number);\n// TODO: walk the array, stop (inclusive) at the first 0\nconsole.log('');\n"}$sc$::jsonb
) on conflict (slug) do nothing;

insert into challenge_test_cases (challenge_id, input, expected_output, is_hidden)
select c.id, v.input, v.expected_output, v.is_hidden from challenges c cross join (values
  ($i$SYNC A
TIMEOUT B 0
PROMISE C
SYNC D$i$, $o$A D C B$o$, false),
  ($i$SYNC X
PROMISE Y
TIMEOUT Z 0$i$, $o$X Y Z$o$, true)
) as v(input, expected_output, is_hidden)
where c.slug = 'node-event-loop-order' and not exists (select 1 from challenge_test_cases tc where tc.challenge_id = c.id);

insert into challenge_test_cases (challenge_id, input, expected_output, is_hidden)
select c.id, v.input, v.expected_output, v.is_hidden from challenges c cross join (values
  ($i$0 100 200 1500 1600
500$i$, $o$2$o$, false),
  ($i$0 600 1200
500$i$, $o$3$o$, true)
) as v(input, expected_output, is_hidden)
where c.slug = 'node-debounce-fires' and not exists (select 1 from challenge_test_cases tc where tc.challenge_id = c.id);

insert into challenge_test_cases (challenge_id, input, expected_output, is_hidden)
select c.id, v.input, v.expected_output, v.is_hidden from challenges c cross join (values
  ($i$1 1 0 1$i$, $o$0 1 2$o$, false),
  ($i$0$i$, $o$0$o$, true),
  ($i$1 1 1$i$, $o$0 1 2$o$, true)
) as v(input, expected_output, is_hidden)
where c.slug = 'node-middleware-chain' and not exists (select 1 from challenge_test_cases tc where tc.challenge_id = c.id);

-- ---------------------------------------------------------------------
-- EXPRESS
-- ---------------------------------------------------------------------
insert into challenges (title, slug, description, difficulty, category_id, estimated_minutes, xp_reward, tags, constraints, input_format, output_format, starter_code)
values (
  'Route Match Priority',
  'express-route-match-priority',
  'Express matches routes in registration order. Given n registered route patterns (segments are either exact or ":param") and one request path, output the 0-based index of the first pattern that matches, or -1 if none match.',
  'medium',
  (select id from challenge_categories where slug = 'express'),
  20, 50,
  array['express', 'routing'],
  '1 <= n <= 1000',
  'Line 1: n. Next n lines: route patterns in registration order. Last line: the request path.',
  'A single integer: the matching index, or -1.',
  $sc${"javascript":"const lines = require('fs').readFileSync(0, 'utf8').trim().split('\\n');\nconst n = Number(lines[0]);\n// TODO: compare segment counts and exact segments (':' segments match anything)\nconsole.log(-1);\n"}$sc$::jsonb
) on conflict (slug) do nothing;

insert into challenges (title, slug, description, difficulty, category_id, estimated_minutes, xp_reward, tags, constraints, input_format, output_format, starter_code)
values (
  'Idempotency Key Deduplication',
  'express-idempotency-dedup',
  'Given a sequence of requests, each with a resource id and a payload hash, classify each as NEW (first time this id has been seen) or DUPLICATE (same id and same payload hash as before).',
  'medium',
  (select id from challenge_categories where slug = 'express'),
  20, 50,
  array['express', 'idempotency'],
  '1 <= n <= 10000',
  'Line 1: n. Next n lines: "id hash".',
  'Space-separated results ("NEW" or "DUPLICATE") in request order.',
  $sc${"javascript":"const lines = require('fs').readFileSync(0, 'utf8').trim().split('\\n');\nconst n = Number(lines[0]);\n// TODO: track a map of id -> last seen hash\nconsole.log('');\n"}$sc$::jsonb
) on conflict (slug) do nothing;

insert into challenges (title, slug, description, difficulty, category_id, estimated_minutes, xp_reward, tags, constraints, input_format, output_format, starter_code)
values (
  'HTTP Status Class Counts',
  'express-status-class-count',
  'Given a list of HTTP status codes, count how many fall into each class: 1xx, 2xx, 3xx, 4xx, 5xx.',
  'easy',
  (select id from challenge_categories where slug = 'express'),
  10, 20,
  array['express', 'http'],
  '1 <= n <= 10000, 100 <= code <= 599',
  'Space-separated status codes.',
  'Five space-separated counts: 1xx 2xx 3xx 4xx 5xx.',
  $sc${"javascript":"const arr = require('fs').readFileSync(0, 'utf8').trim().split(' ').map(Number);\n// TODO: bucket by Math.floor(code/100)\nconsole.log('0 0 0 0 0');\n"}$sc$::jsonb
) on conflict (slug) do nothing;

insert into challenge_test_cases (challenge_id, input, expected_output, is_hidden)
select c.id, v.input, v.expected_output, v.is_hidden from challenges c cross join (values
  ($i$2
/users/new
/users/:id
/users/new$i$, $o$0$o$, false),
  ($i$2
/users/new
/users/:id
/users/42$i$, $o$1$o$, true)
) as v(input, expected_output, is_hidden)
where c.slug = 'express-route-match-priority' and not exists (select 1 from challenge_test_cases tc where tc.challenge_id = c.id);

insert into challenge_test_cases (challenge_id, input, expected_output, is_hidden)
select c.id, v.input, v.expected_output, v.is_hidden from challenges c cross join (values
  ($i$5
a 1
b 1
a 1
c 1
b 1$i$, $o$NEW NEW DUPLICATE NEW DUPLICATE$o$, false)
) as v(input, expected_output, is_hidden)
where c.slug = 'express-idempotency-dedup' and not exists (select 1 from challenge_test_cases tc where tc.challenge_id = c.id);

insert into challenge_test_cases (challenge_id, input, expected_output, is_hidden)
select c.id, v.input, v.expected_output, v.is_hidden from challenges c cross join (values
  ($i$200 404 301 200 500$i$, $o$0 2 1 1 1$o$, false)
) as v(input, expected_output, is_hidden)
where c.slug = 'express-status-class-count' and not exists (select 1 from challenge_test_cases tc where tc.challenge_id = c.id);

-- ---------------------------------------------------------------------
-- NEXT.JS
-- ---------------------------------------------------------------------
insert into challenges (title, slug, description, difficulty, category_id, estimated_minutes, xp_reward, tags, constraints, input_format, output_format, starter_code)
values (
  'Dynamic Route Param Extraction',
  'nextjs-dynamic-param',
  'Given a Next.js-style file-route pattern using [param] segments and an actual URL, extract each dynamic segment''s value in pattern order.',
  'easy',
  (select id from challenge_categories where slug = 'nextjs'),
  15, 20,
  array['nextjs', 'routing'],
  'Pattern and URL always have the same number of segments.',
  'Line 1: the route pattern. Line 2: the actual URL.',
  'Space-separated "name=value" pairs, in pattern order.',
  $sc${"javascript":"const [pattern, url] = require('fs').readFileSync(0, 'utf8').trim().split('\\n');\n// TODO: match '[name]' segments to url segments\nconsole.log('');\n"}$sc$::jsonb
) on conflict (slug) do nothing;

insert into challenges (title, slug, description, difficulty, category_id, estimated_minutes, xp_reward, tags, constraints, input_format, output_format, starter_code)
values (
  'Catch-All Route Segments',
  'nextjs-catch-all',
  'Given a Next.js catch-all route pattern like "/docs/[...slug]" and an actual URL, output the captured segments comma-joined as "name=seg1,seg2,...".',
  'medium',
  (select id from challenge_categories where slug = 'nextjs'),
  15, 50,
  array['nextjs', 'routing'],
  'The pattern has exactly one [...name] segment, which is always the last segment.',
  'Line 1: the route pattern. Line 2: the actual URL.',
  'A single "name=seg1,seg2,..." string.',
  $sc${"javascript":"const [pattern, url] = require('fs').readFileSync(0, 'utf8').trim().split('\\n');\n// TODO: find the '[...name]' segment index, join the remaining url segments with commas\nconsole.log('');\n"}$sc$::jsonb
) on conflict (slug) do nothing;

insert into challenges (title, slug, description, difficulty, category_id, estimated_minutes, xp_reward, tags, constraints, input_format, output_format, starter_code)
values (
  'Middleware Redirect Chain',
  'nextjs-redirect-chain',
  'Given a set of path->path redirect rules and a starting path, follow the chain of redirects until reaching a path with no further rule. If the chain loops (more than 100 hops), output "LOOP".',
  'medium',
  (select id from challenge_categories where slug = 'nextjs'),
  20, 50,
  array['nextjs', 'redirects'],
  '1 <= number of rules <= 1000',
  'Line 1: n. Next n lines: "from to". Last line: the starting path.',
  'The final path, or "LOOP".',
  $sc${"javascript":"const lines = require('fs').readFileSync(0, 'utf8').trim().split('\\n');\nconst n = Number(lines[0]);\n// TODO: follow the map of from->to until no rule exists or 100 hops pass\nconsole.log('LOOP');\n"}$sc$::jsonb
) on conflict (slug) do nothing;

insert into challenge_test_cases (challenge_id, input, expected_output, is_hidden)
select c.id, v.input, v.expected_output, v.is_hidden from challenges c cross join (values
  ($i$/shop/[category]/[id]
/shop/shoes/42$i$, $o$category=shoes id=42$o$, false),
  ($i$/p/[id]
/p/7$i$, $o$id=7$o$, true)
) as v(input, expected_output, is_hidden)
where c.slug = 'nextjs-dynamic-param' and not exists (select 1 from challenge_test_cases tc where tc.challenge_id = c.id);

insert into challenge_test_cases (challenge_id, input, expected_output, is_hidden)
select c.id, v.input, v.expected_output, v.is_hidden from challenges c cross join (values
  ($i$/docs/[...slug]
/docs/a/b/c$i$, $o$slug=a,b,c$o$, false),
  ($i$/files/[...path]
/files/x$i$, $o$path=x$o$, true)
) as v(input, expected_output, is_hidden)
where c.slug = 'nextjs-catch-all' and not exists (select 1 from challenge_test_cases tc where tc.challenge_id = c.id);

insert into challenge_test_cases (challenge_id, input, expected_output, is_hidden)
select c.id, v.input, v.expected_output, v.is_hidden from challenges c cross join (values
  ($i$2
/old /new
/new /newest
/old$i$, $o$/newest$o$, false),
  ($i$2
/a /b
/b /a
/a$i$, $o$LOOP$o$, true)
) as v(input, expected_output, is_hidden)
where c.slug = 'nextjs-redirect-chain' and not exists (select 1 from challenge_test_cases tc where tc.challenge_id = c.id);

-- ---------------------------------------------------------------------
-- AWS
-- ---------------------------------------------------------------------
insert into challenges (title, slug, description, difficulty, category_id, estimated_minutes, xp_reward, tags, constraints, input_format, output_format, starter_code)
values (
  'S3 Tiered Storage Cost',
  'aws-s3-cost',
  'Given GB stored, compute the monthly S3 cost using tiered pricing: first 50GB at $0.023/GB, next 450GB at $0.022/GB, anything beyond at $0.021/GB. Round to 2 decimals.',
  'easy',
  (select id from challenge_categories where slug = 'aws'),
  15, 20,
  array['aws', 's3', 'cost'],
  '0 <= GB <= 100000',
  'A single number: GB stored.',
  'A single number: total cost, 2 decimal places.',
  $sc${"javascript":"const gb = Number(require('fs').readFileSync(0, 'utf8').trim());\n// TODO: apply the three pricing tiers in order\nconsole.log('0.00');\n","python":"gb = float(input())\n# TODO: apply the three pricing tiers in order\nprint('0.00')\n"}$sc$::jsonb
) on conflict (slug) do nothing;

insert into challenges (title, slug, description, difficulty, category_id, estimated_minutes, xp_reward, tags, constraints, input_format, output_format, starter_code)
values (
  'EC2 Instance Right-Sizing',
  'aws-ec2-rightsizing',
  'Given a list of EC2 instance types (name, vCPUs, memory GB, hourly price) and a workload''s required vCPUs/memory, output the cheapest instance type that meets or exceeds both requirements, or "NONE" if no instance qualifies.',
  'medium',
  (select id from challenge_categories where slug = 'aws'),
  20, 50,
  array['aws', 'ec2', 'cost'],
  '1 <= number of instance types <= 100',
  'Line 1: n. Next n lines: "name vcpu mem price". Last line: "reqVcpu reqMem".',
  'The cheapest qualifying instance name, or "NONE".',
  $sc${"javascript":"const lines = require('fs').readFileSync(0, 'utf8').trim().split('\\n');\nconst n = Number(lines[0]);\n// TODO: filter instances meeting both requirements, pick the cheapest\nconsole.log('NONE');\n"}$sc$::jsonb
) on conflict (slug) do nothing;

insert into challenges (title, slug, description, difficulty, category_id, estimated_minutes, xp_reward, tags, constraints, input_format, output_format, starter_code)
values (
  'Auto Scaling Instance Count',
  'aws-autoscale-count',
  'Given the current request rate, the capacity each instance can serve, and min/max instance bounds, compute how many instances an auto-scaling group should run (ceil(requests/capacity), clamped to [min, max]).',
  'easy',
  (select id from challenge_categories where slug = 'aws'),
  15, 20,
  array['aws', 'autoscaling'],
  '1 <= all values <= 1000000',
  'Four space-separated integers: requestsPerSecond capacityPerInstance min max.',
  'A single integer: the instance count.',
  $sc${"javascript":"const [reqps, cap, min, max] = require('fs').readFileSync(0, 'utf8').trim().split(' ').map(Number);\n// TODO: ceil(reqps/cap), then clamp to [min, max]\nconsole.log(0);\n"}$sc$::jsonb
) on conflict (slug) do nothing;

insert into challenge_test_cases (challenge_id, input, expected_output, is_hidden)
select c.id, v.input, v.expected_output, v.is_hidden from challenges c cross join (values
  ($i$100$i$, $o$2.25$o$, false), ($i$10$i$, $o$0.23$o$, true)
) as v(input, expected_output, is_hidden)
where c.slug = 'aws-s3-cost' and not exists (select 1 from challenge_test_cases tc where tc.challenge_id = c.id);

insert into challenge_test_cases (challenge_id, input, expected_output, is_hidden)
select c.id, v.input, v.expected_output, v.is_hidden from challenges c cross join (values
  ($i$3
t3.medium 2 4 0.0416
t3.large 2 8 0.0832
m5.large 2 8 0.096
2 6$i$, $o$t3.large$o$, false)
) as v(input, expected_output, is_hidden)
where c.slug = 'aws-ec2-rightsizing' and not exists (select 1 from challenge_test_cases tc where tc.challenge_id = c.id);

insert into challenge_test_cases (challenge_id, input, expected_output, is_hidden)
select c.id, v.input, v.expected_output, v.is_hidden from challenges c cross join (values
  ($i$250 100 1 5$i$, $o$3$o$, false), ($i$1000 100 1 5$i$, $o$5$o$, true)
) as v(input, expected_output, is_hidden)
where c.slug = 'aws-autoscale-count' and not exists (select 1 from challenge_test_cases tc where tc.challenge_id = c.id);

-- ---------------------------------------------------------------------
-- DOCKER
-- ---------------------------------------------------------------------
insert into challenges (title, slug, description, difficulty, category_id, estimated_minutes, xp_reward, tags, constraints, input_format, output_format, starter_code)
values (
  'Dockerfile Layer Count',
  'docker-layer-count',
  'Given the lines of a Dockerfile, count how many instructions create a new image layer: FROM, RUN, COPY, and ADD each do; other instructions (CMD, ENV, EXPOSE, WORKDIR, LABEL, ...) do not in this simplified model.',
  'easy',
  (select id from challenge_categories where slug = 'docker'),
  10, 20,
  array['docker', 'dockerfile'],
  '1 <= number of lines <= 1000',
  'Line 1: n. Next n lines: Dockerfile instructions.',
  'A single integer: the layer count.',
  $sc${"javascript":"const lines = require('fs').readFileSync(0, 'utf8').trim().split('\\n');\nconst n = Number(lines[0]);\n// TODO: count lines starting with FROM/RUN/COPY/ADD\nconsole.log(0);\n"}$sc$::jsonb
) on conflict (slug) do nothing;

insert into challenges (title, slug, description, difficulty, category_id, estimated_minutes, xp_reward, tags, constraints, input_format, output_format, starter_code)
values (
  'Detect Exposed Port',
  'docker-exposed-port',
  'Given the lines of a Dockerfile, find the port number in the EXPOSE instruction. Output -1 if there is no EXPOSE line.',
  'easy',
  (select id from challenge_categories where slug = 'docker'),
  10, 20,
  array['docker', 'dockerfile'],
  '1 <= number of lines <= 1000',
  'Line 1: n. Next n lines: Dockerfile instructions.',
  'A single integer: the exposed port, or -1.',
  $sc${"javascript":"const lines = require('fs').readFileSync(0, 'utf8').trim().split('\\n');\nconst n = Number(lines[0]);\n// TODO: find the line starting with EXPOSE\nconsole.log(-1);\n"}$sc$::jsonb
) on conflict (slug) do nothing;

insert into challenges (title, slug, description, difficulty, category_id, estimated_minutes, xp_reward, tags, constraints, input_format, output_format, starter_code)
values (
  'Layer Cache Invalidation',
  'docker-cache-invalidation',
  'A Dockerfile has n instructions. If the instruction at 0-based index `changedIndex` changes, Docker''s layer cache invalidates that layer and every layer after it. Output how many layers must be rebuilt.',
  'easy',
  (select id from challenge_categories where slug = 'docker'),
  10, 20,
  array['docker', 'caching'],
  '1 <= n <= 1000, 0 <= changedIndex < n',
  'Two space-separated integers: n changedIndex.',
  'A single integer: the number of layers to rebuild.',
  $sc${"javascript":"const [n, idx] = require('fs').readFileSync(0, 'utf8').trim().split(' ').map(Number);\n// TODO\nconsole.log(0);\n"}$sc$::jsonb
) on conflict (slug) do nothing;

insert into challenge_test_cases (challenge_id, input, expected_output, is_hidden)
select c.id, v.input, v.expected_output, v.is_hidden from challenges c cross join (values
  ($i$4
FROM node
RUN npm install
COPY . .
CMD ["node","index.js"]$i$, $o$3$o$, false),
  ($i$4
FROM python
RUN pip install
RUN echo hi
ENV X=1$i$, $o$3$o$, true)
) as v(input, expected_output, is_hidden)
where c.slug = 'docker-layer-count' and not exists (select 1 from challenge_test_cases tc where tc.challenge_id = c.id);

insert into challenge_test_cases (challenge_id, input, expected_output, is_hidden)
select c.id, v.input, v.expected_output, v.is_hidden from challenges c cross join (values
  ($i$3
FROM node
EXPOSE 8080
CMD ["node"]$i$, $o$8080$o$, false),
  ($i$2
FROM node
CMD ["node"]$i$, $o$-1$o$, true)
) as v(input, expected_output, is_hidden)
where c.slug = 'docker-exposed-port' and not exists (select 1 from challenge_test_cases tc where tc.challenge_id = c.id);

insert into challenge_test_cases (challenge_id, input, expected_output, is_hidden)
select c.id, v.input, v.expected_output, v.is_hidden from challenges c cross join (values
  ($i$5 2$i$, $o$3$o$, false), ($i$4 0$i$, $o$4$o$, true)
) as v(input, expected_output, is_hidden)
where c.slug = 'docker-cache-invalidation' and not exists (select 1 from challenge_test_cases tc where tc.challenge_id = c.id);

-- ---------------------------------------------------------------------
-- KUBERNETES
-- ---------------------------------------------------------------------
insert into challenges (title, slug, description, difficulty, category_id, estimated_minutes, xp_reward, tags, constraints, input_format, output_format, starter_code)
values (
  'Pod Bin Packing',
  'k8s-pod-bin-packing',
  'Given identical-capacity nodes and a list of pod CPU requests (in the given order), schedule pods using first-fit (place each pod on the first node with enough remaining capacity; open a new node if none fit). Output the number of nodes used.',
  'medium',
  (select id from challenge_categories where slug = 'kubernetes'),
  20, 50,
  array['kubernetes', 'scheduling'],
  '1 <= number of pods <= 10000',
  'Line 1: node capacity. Line 2: space-separated pod CPU requests.',
  'A single integer: the number of nodes used.',
  $sc${"javascript":"const lines = require('fs').readFileSync(0, 'utf8').trim().split('\\n');\nconst capacity = Number(lines[0]);\nconst pods = lines[1].trim().split(' ').map(Number);\n// TODO: first-fit bin packing\nconsole.log(0);\n"}$sc$::jsonb
) on conflict (slug) do nothing;

insert into challenges (title, slug, description, difficulty, category_id, estimated_minutes, xp_reward, tags, constraints, input_format, output_format, starter_code)
values (
  'Replica Health Check',
  'k8s-replica-health',
  'Given the desired replica count and the number of currently healthy/running replicas, output "HEALTHY" if running >= desired, else "DEGRADED".',
  'easy',
  (select id from challenge_categories where slug = 'kubernetes'),
  5, 20,
  array['kubernetes', 'health-checks'],
  '0 <= running, desired <= 10000',
  'Two space-separated integers: desired running.',
  '"HEALTHY" or "DEGRADED".',
  $sc${"javascript":"const [desired, running] = require('fs').readFileSync(0, 'utf8').trim().split(' ').map(Number);\n// TODO\nconsole.log('DEGRADED');\n"}$sc$::jsonb
) on conflict (slug) do nothing;

insert into challenges (title, slug, description, difficulty, category_id, estimated_minutes, xp_reward, tags, constraints, input_format, output_format, starter_code)
values (
  'Rolling Update Max Unavailable',
  'k8s-rolling-update-unavailable',
  'Given the total replica count and a maxUnavailable percentage, compute how many pods can be taken down simultaneously during a rolling update: floor(total * pct / 100).',
  'easy',
  (select id from challenge_categories where slug = 'kubernetes'),
  10, 20,
  array['kubernetes', 'deployments'],
  '0 <= total <= 100000, 0 <= pct <= 100',
  'Two space-separated integers: total pct.',
  'A single integer.',
  $sc${"javascript":"const [total, pct] = require('fs').readFileSync(0, 'utf8').trim().split(' ').map(Number);\n// TODO\nconsole.log(0);\n"}$sc$::jsonb
) on conflict (slug) do nothing;

insert into challenge_test_cases (challenge_id, input, expected_output, is_hidden)
select c.id, v.input, v.expected_output, v.is_hidden from challenges c cross join (values
  ($i$10
4 6 3 7 2$i$, $o$3$o$, false)
) as v(input, expected_output, is_hidden)
where c.slug = 'k8s-pod-bin-packing' and not exists (select 1 from challenge_test_cases tc where tc.challenge_id = c.id);

insert into challenge_test_cases (challenge_id, input, expected_output, is_hidden)
select c.id, v.input, v.expected_output, v.is_hidden from challenges c cross join (values
  ($i$3 3$i$, $o$HEALTHY$o$, false), ($i$3 2$i$, $o$DEGRADED$o$, true)
) as v(input, expected_output, is_hidden)
where c.slug = 'k8s-replica-health' and not exists (select 1 from challenge_test_cases tc where tc.challenge_id = c.id);

insert into challenge_test_cases (challenge_id, input, expected_output, is_hidden)
select c.id, v.input, v.expected_output, v.is_hidden from challenges c cross join (values
  ($i$10 25$i$, $o$2$o$, false), ($i$4 10$i$, $o$0$o$, true)
) as v(input, expected_output, is_hidden)
where c.slug = 'k8s-rolling-update-unavailable' and not exists (select 1 from challenge_test_cases tc where tc.challenge_id = c.id);

-- ---------------------------------------------------------------------
-- DEVOPS
-- ---------------------------------------------------------------------
insert into challenges (title, slug, description, difficulty, category_id, estimated_minutes, xp_reward, tags, constraints, input_format, output_format, starter_code)
values (
  'Build Pipeline Topological Order',
  'devops-pipeline-topo-order',
  'A CI pipeline has n stages (0-indexed) and m "b a" dependency pairs meaning stage b must run before stage a. Output a valid execution order: at every step, run the lowest-indexed stage among those currently ready (Kahn''s algorithm, ties broken by smallest index).',
  'hard',
  (select id from challenge_categories where slug = 'devops'),
  30, 100,
  array['devops', 'ci-cd', 'graphs'],
  '1 <= n <= 1000, the dependency graph is acyclic',
  'Line 1: n. Line 2: m. Next m lines: "b a" (b before a).',
  'Space-separated stage indices in execution order.',
  $sc${"javascript":"const lines = require('fs').readFileSync(0, 'utf8').trim().split('\\n');\nconst n = Number(lines[0]);\nconst m = Number(lines[1]);\n// TODO: Kahn's algorithm, always picking the smallest-index ready stage\nconsole.log('');\n"}$sc$::jsonb
) on conflict (slug) do nothing;

insert into challenges (title, slug, description, difficulty, category_id, estimated_minutes, xp_reward, tags, constraints, input_format, output_format, starter_code)
values (
  'Canary Rollout Split',
  'devops-canary-split',
  'Given the total instance count and a canary percentage, compute how many instances get canary traffic (floor) and how many remain on the stable version.',
  'easy',
  (select id from challenge_categories where slug = 'devops'),
  10, 20,
  array['devops', 'deployments'],
  '0 <= total <= 100000, 0 <= pct <= 100',
  'Two space-separated integers: total pct.',
  'Two space-separated integers: canaryCount stableCount.',
  $sc${"javascript":"const [total, pct] = require('fs').readFileSync(0, 'utf8').trim().split(' ').map(Number);\n// TODO\nconsole.log('0 0');\n"}$sc$::jsonb
) on conflict (slug) do nothing;

insert into challenges (title, slug, description, difficulty, category_id, estimated_minutes, xp_reward, tags, constraints, input_format, output_format, starter_code)
values (
  'Blue-Green Switch Validation',
  'devops-bluegreen-check',
  'Given health-check results (1 = healthy, 0 = unhealthy) for every instance in the "green" environment, output "SWITCH" if all instances are healthy, otherwise "ABORT".',
  'easy',
  (select id from challenge_categories where slug = 'devops'),
  10, 20,
  array['devops', 'deployments'],
  '1 <= number of instances <= 10000',
  'Space-separated 0/1 health results.',
  '"SWITCH" or "ABORT".',
  $sc${"javascript":"const arr = require('fs').readFileSync(0, 'utf8').trim().split(' ').map(Number);\n// TODO\nconsole.log('ABORT');\n"}$sc$::jsonb
) on conflict (slug) do nothing;

insert into challenge_test_cases (challenge_id, input, expected_output, is_hidden)
select c.id, v.input, v.expected_output, v.is_hidden from challenges c cross join (values
  ($i$4
3
1 0
2 0
3 2$i$, $o$1 3 2 0$o$, false)
) as v(input, expected_output, is_hidden)
where c.slug = 'devops-pipeline-topo-order' and not exists (select 1 from challenge_test_cases tc where tc.challenge_id = c.id);

insert into challenge_test_cases (challenge_id, input, expected_output, is_hidden)
select c.id, v.input, v.expected_output, v.is_hidden from challenges c cross join (values
  ($i$20 10$i$, $o$2 18$o$, false), ($i$7 50$i$, $o$3 4$o$, true)
) as v(input, expected_output, is_hidden)
where c.slug = 'devops-canary-split' and not exists (select 1 from challenge_test_cases tc where tc.challenge_id = c.id);

insert into challenge_test_cases (challenge_id, input, expected_output, is_hidden)
select c.id, v.input, v.expected_output, v.is_hidden from challenges c cross join (values
  ($i$1 1 1$i$, $o$SWITCH$o$, false), ($i$1 0 1$i$, $o$ABORT$o$, true)
) as v(input, expected_output, is_hidden)
where c.slug = 'devops-bluegreen-check' and not exists (select 1 from challenge_test_cases tc where tc.challenge_id = c.id);

-- ---------------------------------------------------------------------
-- DATABASES
-- ---------------------------------------------------------------------
insert into challenges (title, slug, description, difficulty, category_id, estimated_minutes, xp_reward, tags, constraints, input_format, output_format, starter_code)
values (
  'Index Selectivity',
  'db-index-selectivity',
  'Given the total row count and the number of distinct values in a column, compute its selectivity (distinct/total), rounded to 4 decimals — a common metric for deciding whether a column is a good index candidate.',
  'easy',
  (select id from challenge_categories where slug = 'databases'),
  10, 20,
  array['databases', 'indexing'],
  '1 <= distinct <= total <= 10^9',
  'Two space-separated integers: total distinct.',
  'A single number, 4 decimal places.',
  $sc${"javascript":"const [total, distinct] = require('fs').readFileSync(0, 'utf8').trim().split(' ').map(Number);\n// TODO\nconsole.log('0.0000');\n"}$sc$::jsonb
) on conflict (slug) do nothing;

insert into challenges (title, slug, description, difficulty, category_id, estimated_minutes, xp_reward, tags, constraints, input_format, output_format, starter_code)
values (
  'Deadlock Detection',
  'db-deadlock-detect',
  'Given a wait-for graph between transactions ("A B" means transaction A is waiting on transaction B), determine whether a deadlock exists (a cycle in the graph). Output "DEADLOCK" or "OK".',
  'medium',
  (select id from challenge_categories where slug = 'databases'),
  20, 50,
  array['databases', 'transactions', 'graphs'],
  '1 <= number of edges <= 1000',
  'Line 1: number of edges m. Next m lines: "A B".',
  '"DEADLOCK" or "OK".',
  $sc${"javascript":"const lines = require('fs').readFileSync(0, 'utf8').trim().split('\\n');\nconst m = Number(lines[0]);\n// TODO: cycle detection (DFS with a recursion-stack set) on the wait-for graph\nconsole.log('OK');\n"}$sc$::jsonb
) on conflict (slug) do nothing;

insert into challenges (title, slug, description, difficulty, category_id, estimated_minutes, xp_reward, tags, constraints, input_format, output_format, starter_code)
values (
  'Query Filter Row Count',
  'db-query-filter-count',
  'Given n integer values and a threshold, count how many rows satisfy "value > threshold" — the basic semantics of a WHERE clause.',
  'easy',
  (select id from challenge_categories where slug = 'databases'),
  10, 20,
  array['databases', 'sql'],
  '1 <= n <= 100000',
  'Line 1: n space-separated integers. Line 2: threshold.',
  'A single integer: the matching row count.',
  $sc${"javascript":"const lines = require('fs').readFileSync(0, 'utf8').trim().split('\\n');\nconst arr = lines[0].trim().split(' ').map(Number);\nconst threshold = Number(lines[1].trim());\n// TODO\nconsole.log(0);\n"}$sc$::jsonb
) on conflict (slug) do nothing;

insert into challenge_test_cases (challenge_id, input, expected_output, is_hidden)
select c.id, v.input, v.expected_output, v.is_hidden from challenges c cross join (values
  ($i$1000 950$i$, $o$0.9500$o$, false), ($i$1000 2$i$, $o$0.0020$o$, true)
) as v(input, expected_output, is_hidden)
where c.slug = 'db-index-selectivity' and not exists (select 1 from challenge_test_cases tc where tc.challenge_id = c.id);

insert into challenge_test_cases (challenge_id, input, expected_output, is_hidden)
select c.id, v.input, v.expected_output, v.is_hidden from challenges c cross join (values
  ($i$3
1 2
2 3
3 1$i$, $o$DEADLOCK$o$, false),
  ($i$2
1 2
2 3$i$, $o$OK$o$, true)
) as v(input, expected_output, is_hidden)
where c.slug = 'db-deadlock-detect' and not exists (select 1 from challenge_test_cases tc where tc.challenge_id = c.id);

insert into challenge_test_cases (challenge_id, input, expected_output, is_hidden)
select c.id, v.input, v.expected_output, v.is_hidden from challenges c cross join (values
  ($i$5 10 15 3 20
10$i$, $o$2$o$, false),
  ($i$1 2 3
5$i$, $o$0$o$, true)
) as v(input, expected_output, is_hidden)
where c.slug = 'db-query-filter-count' and not exists (select 1 from challenge_test_cases tc where tc.challenge_id = c.id);

-- ---------------------------------------------------------------------
-- REST APIS
-- ---------------------------------------------------------------------
insert into challenges (title, slug, description, difficulty, category_id, estimated_minutes, xp_reward, tags, constraints, input_format, output_format, starter_code)
values (
  'Idempotent PUT Classification',
  'rest-idempotency-put',
  'Given a sequence of PUT requests, each with a resource id and a payload hash, classify each request: "FIRST" (id not seen before), "REPEAT" (same id, same payload — an idempotent retry), or "CONFLICT" (same id, different payload).',
  'medium',
  (select id from challenge_categories where slug = 'rest-apis'),
  20, 50,
  array['rest-apis', 'idempotency'],
  '1 <= n <= 10000',
  'Line 1: n. Next n lines: "id hash".',
  'Space-separated classifications in request order.',
  $sc${"javascript":"const lines = require('fs').readFileSync(0, 'utf8').trim().split('\\n');\nconst n = Number(lines[0]);\n// TODO\nconsole.log('');\n"}$sc$::jsonb
) on conflict (slug) do nothing;

insert into challenges (title, slug, description, difficulty, category_id, estimated_minutes, xp_reward, tags, constraints, input_format, output_format, starter_code)
values (
  'Sliding Window Rate Limit',
  'rest-rate-limit-429',
  'Given a request limit per 60-second sliding window and a list of request timestamps (seconds, ascending), classify each request as "ALLOWED" or "429". A request counts toward the window only if it was itself allowed.',
  'hard',
  (select id from challenge_categories where slug = 'rest-apis'),
  25, 100,
  array['rest-apis', 'rate-limiting'],
  '1 <= limit <= 10000, 1 <= number of requests <= 10000',
  'Line 1: limit windowSeconds. Line 2: space-separated ascending timestamps.',
  'Space-separated classifications in request order.',
  $sc${"javascript":"const lines = require('fs').readFileSync(0, 'utf8').trim().split('\\n');\nconst [limit, windowSec] = lines[0].trim().split(' ').map(Number);\nconst timestamps = lines[1].trim().split(' ').map(Number);\n// TODO: for each timestamp, count already-ALLOWED requests within (t - windowSec, t]\nconsole.log('');\n"}$sc$::jsonb
) on conflict (slug) do nothing;

insert into challenges (title, slug, description, difficulty, category_id, estimated_minutes, xp_reward, tags, constraints, input_format, output_format, starter_code)
values (
  'Pagination Item Count',
  'rest-pagination-count',
  'Given the total number of items, a page size, and a 1-indexed page number, output how many items are returned on that page (fewer on the last page, 0 if the page is beyond the data).',
  'easy',
  (select id from challenge_categories where slug = 'rest-apis'),
  10, 20,
  array['rest-apis', 'pagination'],
  '0 <= total <= 10^9, 1 <= pageSize, page',
  'Three space-separated integers: total pageSize page.',
  'A single integer: item count on that page.',
  $sc${"javascript":"const [total, pageSize, page] = require('fs').readFileSync(0, 'utf8').trim().split(' ').map(Number);\n// TODO\nconsole.log(0);\n"}$sc$::jsonb
) on conflict (slug) do nothing;

insert into challenge_test_cases (challenge_id, input, expected_output, is_hidden)
select c.id, v.input, v.expected_output, v.is_hidden from challenges c cross join (values
  ($i$4
1 abc
1 abc
1 xyz
2 abc$i$, $o$FIRST REPEAT CONFLICT FIRST$o$, false)
) as v(input, expected_output, is_hidden)
where c.slug = 'rest-idempotency-put' and not exists (select 1 from challenge_test_cases tc where tc.challenge_id = c.id);

insert into challenge_test_cases (challenge_id, input, expected_output, is_hidden)
select c.id, v.input, v.expected_output, v.is_hidden from challenges c cross join (values
  ($i$3 60
0 10 20 30 50$i$, $o$ALLOWED ALLOWED ALLOWED 429 429$o$, false),
  ($i$2 60
0 5 70$i$, $o$ALLOWED ALLOWED ALLOWED$o$, true)
) as v(input, expected_output, is_hidden)
where c.slug = 'rest-rate-limit-429' and not exists (select 1 from challenge_test_cases tc where tc.challenge_id = c.id);

insert into challenge_test_cases (challenge_id, input, expected_output, is_hidden)
select c.id, v.input, v.expected_output, v.is_hidden from challenges c cross join (values
  ($i$25 10 3$i$, $o$5$o$, false), ($i$25 10 1$i$, $o$10$o$, true), ($i$25 10 4$i$, $o$0$o$, true)
) as v(input, expected_output, is_hidden)
where c.slug = 'rest-pagination-count' and not exists (select 1 from challenge_test_cases tc where tc.challenge_id = c.id);

-- ---------------------------------------------------------------------
-- MACHINE LEARNING
-- ---------------------------------------------------------------------
insert into challenges (title, slug, description, difficulty, category_id, estimated_minutes, xp_reward, tags, constraints, input_format, output_format, starter_code)
values (
  'Confusion Matrix Metrics',
  'ml-confusion-matrix',
  'Given TP, FP, FN, TN counts from a binary classifier, compute accuracy, precision, and recall (each rounded to 2 decimals; 0.00 if the denominator is 0).',
  'easy',
  (select id from challenge_categories where slug = 'machine-learning'),
  15, 20,
  array['machine-learning', 'evaluation'],
  '0 <= TP, FP, FN, TN <= 10^9',
  'Four space-separated integers: TP FP FN TN.',
  'Three space-separated numbers: accuracy precision recall.',
  $sc${"javascript":"const [tp, fp, fn, tn] = require('fs').readFileSync(0, 'utf8').trim().split(' ').map(Number);\n// TODO\nconsole.log('0.00 0.00 0.00');\n","python":"tp, fp, fn, tn = map(int, input().split())\n# TODO\nprint('0.00 0.00 0.00')\n"}$sc$::jsonb
) on conflict (slug) do nothing;

insert into challenges (title, slug, description, difficulty, category_id, estimated_minutes, xp_reward, tags, constraints, input_format, output_format, starter_code)
values (
  '1D K-Nearest-Neighbor (k=1)',
  'ml-knn-1d',
  'Given n labeled 1D training points and a query value, classify the query using 1-nearest-neighbor (Euclidean/absolute distance; ties broken by the smaller training value).',
  'medium',
  (select id from challenge_categories where slug = 'machine-learning'),
  20, 50,
  array['machine-learning', 'knn'],
  '1 <= n <= 10000',
  'Line 1: n. Next n lines: "value label". Last line: the query value.',
  'The predicted label.',
  $sc${"javascript":"const lines = require('fs').readFileSync(0, 'utf8').trim().split('\\n');\nconst n = Number(lines[0]);\n// TODO: find the training point with minimum |query - value|\nconsole.log('');\n"}$sc$::jsonb
) on conflict (slug) do nothing;

insert into challenges (title, slug, description, difficulty, category_id, estimated_minutes, xp_reward, tags, constraints, input_format, output_format, starter_code)
values (
  'Entropy of a Binary Split',
  'ml-entropy-split',
  'Given counts of positive and negative examples, compute the Shannon entropy of the split: -p*log2(p) - q*log2(q), where p and q are the class proportions. Round to 4 decimals (0.0000 if pure or empty).',
  'medium',
  (select id from challenge_categories where slug = 'machine-learning'),
  20, 50,
  array['machine-learning', 'decision-trees'],
  '0 <= pos, neg <= 10^9',
  'Two space-separated integers: pos neg.',
  'A single number, 4 decimal places.',
  $sc${"javascript":"const [pos, neg] = require('fs').readFileSync(0, 'utf8').trim().split(' ').map(Number);\n// TODO\nconsole.log('0.0000');\n","python":"pos, neg = map(int, input().split())\n# TODO\nprint('0.0000')\n"}$sc$::jsonb
) on conflict (slug) do nothing;

insert into challenge_test_cases (challenge_id, input, expected_output, is_hidden)
select c.id, v.input, v.expected_output, v.is_hidden from challenges c cross join (values
  ($i$50 10 5 35$i$, $o$0.85 0.83 0.91$o$, false),
  ($i$0 0 10 90$i$, $o$0.90 0.00 0.00$o$, true)
) as v(input, expected_output, is_hidden)
where c.slug = 'ml-confusion-matrix' and not exists (select 1 from challenge_test_cases tc where tc.challenge_id = c.id);

insert into challenge_test_cases (challenge_id, input, expected_output, is_hidden)
select c.id, v.input, v.expected_output, v.is_hidden from challenges c cross join (values
  ($i$3
1 A
5 B
9 C
6$i$, $o$B$o$, false),
  ($i$2
2 X
8 Y
5$i$, $o$X$o$, true)
) as v(input, expected_output, is_hidden)
where c.slug = 'ml-knn-1d' and not exists (select 1 from challenge_test_cases tc where tc.challenge_id = c.id);

insert into challenge_test_cases (challenge_id, input, expected_output, is_hidden)
select c.id, v.input, v.expected_output, v.is_hidden from challenges c cross join (values
  ($i$9 5$i$, $o$0.9403$o$, false), ($i$1 0$i$, $o$0.0000$o$, true)
) as v(input, expected_output, is_hidden)
where c.slug = 'ml-entropy-split' and not exists (select 1 from challenge_test_cases tc where tc.challenge_id = c.id);

-- ---------------------------------------------------------------------
-- DATA SCIENCE
-- ---------------------------------------------------------------------
insert into challenges (title, slug, description, difficulty, category_id, estimated_minutes, xp_reward, tags, constraints, input_format, output_format, starter_code)
values (
  'Mean, Median, Mode',
  'ds-mean-median-mode',
  'Given n integers, compute the mean (2 decimals), median (2 decimals), and mode (the most frequent value; smallest value wins ties).',
  'easy',
  (select id from challenge_categories where slug = 'data-science'),
  15, 20,
  array['data-science', 'statistics'],
  '1 <= n <= 100000',
  'n space-separated integers.',
  'Three space-separated values: mean median mode.',
  $sc${"javascript":"const arr = require('fs').readFileSync(0, 'utf8').trim().split(' ').map(Number);\n// TODO\nconsole.log('0.00 0.00 0');\n","python":"arr = list(map(int, input().split()))\n# TODO\nprint('0.00 0.00 0')\n"}$sc$::jsonb
) on conflict (slug) do nothing;

insert into challenges (title, slug, description, difficulty, category_id, estimated_minutes, xp_reward, tags, constraints, input_format, output_format, starter_code)
values (
  'Z-Score Outlier Count',
  'ds-zscore-outliers',
  'Given n numeric values, compute the mean and population standard deviation, then count how many values have an absolute z-score strictly greater than 2.',
  'medium',
  (select id from challenge_categories where slug = 'data-science'),
  20, 50,
  array['data-science', 'statistics'],
  '2 <= n <= 100000',
  'n space-separated numbers.',
  'A single integer: the outlier count.',
  $sc${"javascript":"const arr = require('fs').readFileSync(0, 'utf8').trim().split(' ').map(Number);\n// TODO: mean, population variance/stddev, then count |z| > 2\nconsole.log(0);\n","python":"arr = list(map(float, input().split()))\n# TODO\nprint(0)\n"}$sc$::jsonb
) on conflict (slug) do nothing;

insert into challenges (title, slug, description, difficulty, category_id, estimated_minutes, xp_reward, tags, constraints, input_format, output_format, starter_code)
values (
  'Linear Regression Slope',
  'ds-linear-regression-slope',
  'Given n (x, y) points, compute the least-squares linear regression slope: (nΣxy - ΣxΣy) / (nΣx² - (Σx)²), rounded to 2 decimals.',
  'medium',
  (select id from challenge_categories where slug = 'data-science'),
  20, 50,
  array['data-science', 'regression'],
  '2 <= n <= 100000, x values are not all identical',
  'Line 1: n. Next n lines: "x y".',
  'A single number: the slope, 2 decimal places.',
  $sc${"javascript":"const lines = require('fs').readFileSync(0, 'utf8').trim().split('\\n');\nconst n = Number(lines[0]);\n// TODO: least-squares slope formula\nconsole.log('0.00');\n","python":"n = int(input())\npoints = [tuple(map(float, input().split())) for _ in range(n)]\n# TODO\nprint('0.00')\n"}$sc$::jsonb
) on conflict (slug) do nothing;

insert into challenge_test_cases (challenge_id, input, expected_output, is_hidden)
select c.id, v.input, v.expected_output, v.is_hidden from challenges c cross join (values
  ($i$1 2 2 3 4$i$, $o$2.40 2.00 2$o$, false),
  ($i$5 1 1 5$i$, $o$3.00 3.00 1$o$, true)
) as v(input, expected_output, is_hidden)
where c.slug = 'ds-mean-median-mode' and not exists (select 1 from challenge_test_cases tc where tc.challenge_id = c.id);

insert into challenge_test_cases (challenge_id, input, expected_output, is_hidden)
select c.id, v.input, v.expected_output, v.is_hidden from challenges c cross join (values
  ($i$2 4 4 4 5 5 7 9$i$, $o$0$o$, false),
  ($i$10 10 10 10 10 10 10 10 10 100$i$, $o$1$o$, true)
) as v(input, expected_output, is_hidden)
where c.slug = 'ds-zscore-outliers' and not exists (select 1 from challenge_test_cases tc where tc.challenge_id = c.id);

insert into challenge_test_cases (challenge_id, input, expected_output, is_hidden)
select c.id, v.input, v.expected_output, v.is_hidden from challenges c cross join (values
  ($i$4
1 2
2 4
3 6
4 8$i$, $o$2.00$o$, false),
  ($i$3
1 1
2 2
3 4$i$, $o$1.50$o$, true)
) as v(input, expected_output, is_hidden)
where c.slug = 'ds-linear-regression-slope' and not exists (select 1 from challenge_test_cases tc where tc.challenge_id = c.id);

-- ---------------------------------------------------------------------
-- ARTIFICIAL INTELLIGENCE
-- ---------------------------------------------------------------------
insert into challenges (title, slug, description, difficulty, category_id, estimated_minutes, xp_reward, tags, constraints, input_format, output_format, starter_code)
values (
  'A* Heuristic Admissibility Check',
  'ai-heuristic-admissible',
  'Given the true shortest-path distance and a heuristic estimate for each node to the goal, determine whether the heuristic is admissible (never overestimates the true distance for any node).',
  'easy',
  (select id from challenge_categories where slug = 'artificial-intelligence'),
  15, 20,
  array['artificial-intelligence', 'search'],
  '1 <= number of nodes <= 10000',
  'Line 1: space-separated true distances. Line 2: space-separated heuristic values.',
  '"ADMISSIBLE" or "INADMISSIBLE".',
  $sc${"javascript":"const lines = require('fs').readFileSync(0, 'utf8').trim().split('\\n');\nconst actual = lines[0].trim().split(' ').map(Number);\nconst heuristic = lines[1].trim().split(' ').map(Number);\n// TODO\nconsole.log('ADMISSIBLE');\n"}$sc$::jsonb
) on conflict (slug) do nothing;

insert into challenges (title, slug, description, difficulty, category_id, estimated_minutes, xp_reward, tags, constraints, input_format, output_format, starter_code)
values (
  'Single Perceptron Step',
  'ai-perceptron-step',
  'Given weights w1, w2, a bias b, and inputs x1, x2, compute the perceptron''s binary output: 1 if w1*x1 + w2*x2 + b >= 0, otherwise 0.',
  'easy',
  (select id from challenge_categories where slug = 'artificial-intelligence'),
  10, 20,
  array['artificial-intelligence', 'neural-networks'],
  'All values are real numbers.',
  'Five space-separated numbers: w1 w2 b x1 x2.',
  '"1" or "0".',
  $sc${"javascript":"const [w1, w2, b, x1, x2] = require('fs').readFileSync(0, 'utf8').trim().split(' ').map(Number);\n// TODO\nconsole.log('0');\n"}$sc$::jsonb
) on conflict (slug) do nothing;

insert into challenges (title, slug, description, difficulty, category_id, estimated_minutes, xp_reward, tags, constraints, input_format, output_format, starter_code)
values (
  'BFS Shortest Path in a Grid',
  'ai-bfs-grid-path',
  'Given a grid of 0s (open) and 1s (wall), find the length of the shortest path (number of steps, moving up/down/left/right) from a start cell to an end cell using breadth-first search. Output -1 if unreachable.',
  'medium',
  (select id from challenge_categories where slug = 'artificial-intelligence'),
  25, 50,
  array['artificial-intelligence', 'search', 'graphs'],
  '1 <= rows, cols <= 200',
  'Line 1: rows cols. Next `rows` lines: `cols` space-separated 0/1 values. Last line: startRow startCol endRow endCol.',
  'A single integer: shortest path length, or -1.',
  $sc${"javascript":"const lines = require('fs').readFileSync(0, 'utf8').trim().split('\\n');\nconst [rows, cols] = lines[0].trim().split(' ').map(Number);\n// TODO: BFS from start to end, avoiding walls (1s)\nconsole.log(-1);\n"}$sc$::jsonb
) on conflict (slug) do nothing;

insert into challenge_test_cases (challenge_id, input, expected_output, is_hidden)
select c.id, v.input, v.expected_output, v.is_hidden from challenges c cross join (values
  ($i$5 3 0
4 3 0$i$, $o$ADMISSIBLE$o$, false),
  ($i$5 3 0
6 3 0$i$, $o$INADMISSIBLE$o$, true)
) as v(input, expected_output, is_hidden)
where c.slug = 'ai-heuristic-admissible' and not exists (select 1 from challenge_test_cases tc where tc.challenge_id = c.id);

insert into challenge_test_cases (challenge_id, input, expected_output, is_hidden)
select c.id, v.input, v.expected_output, v.is_hidden from challenges c cross join (values
  ($i$1 1 -1.5 1 1$i$, $o$1$o$, false),
  ($i$1 1 -1.5 0 1$i$, $o$0$o$, true)
) as v(input, expected_output, is_hidden)
where c.slug = 'ai-perceptron-step' and not exists (select 1 from challenge_test_cases tc where tc.challenge_id = c.id);

insert into challenge_test_cases (challenge_id, input, expected_output, is_hidden)
select c.id, v.input, v.expected_output, v.is_hidden from challenges c cross join (values
  ($i$2 2
0 0
0 0
0 0 1 1$i$, $o$2$o$, false),
  ($i$2 2
0 1
1 0
0 0 1 1$i$, $o$-1$o$, true)
) as v(input, expected_output, is_hidden)
where c.slug = 'ai-bfs-grid-path' and not exists (select 1 from challenge_test_cases tc where tc.challenge_id = c.id);
